### PR TITLE
potential fix for log file being linked more than once

### PR DESCRIPTION
**Pull request by ionox0**
Potential fix for https://github.com/DataBiosphere/toil/issues/3129

### CODE REVIEW

**Comment by adamnovak** [comment]
The tests for this hit https://github.com/DataBiosphere/toil/issues/3127 again.

**Comment by adamnovak** [comment]
@ionox0 Did this actually fix #3129?

**Comment by ionox0** [comment]
For our workflow it completes successfully after this change, however we also normally use `--disableChaining` to avoid this issue

Can you help us to understand the purpose of using symlinks for log files so we can look into this?

**Comment by DailyDreaming** [comment]
@ionox0 Adam may have more context, but I'm not sure symlinking is necessary for log files.  Looking at the original PR I don't believe they explained it: https://github.com/DataBiosphere/toil/pull/1304/files

I'm guessing, but it may simply be a reference when searching a directory for that worker's log file.  So when multiple workers share a log file, a bunch of symlinks are created, one for each worker's name, as a way to find that worker's log file?  I'm guessing that's how it reaps the correct log file at the end when it sees that a worker has failed.  If that's the case, I would support reworking how we log.

**Pull request merged**
