### PR TITLE
Issues/3819 python310

### LINKED ISSUE #3819: Add Python 3.10 testing.
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1043)
┆friendlyId: TOIL-1043

### PR DESCRIPTION
**Pull request by Hexotical**
This will fix #3819.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

* CI testing now covers Python 3.10

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
Rerunning tests with the updated CI/CD image.

**Review by adamnovak — APPROVED** [review]
I think this looks good.

@DailyDreaming Do we actually want to drop the other Python versions from the main tests? Should we maybe keep 3.7 so we do the highest and lowest ostensibly supported versions?

**Comment by DailyDreaming** [comment]
> I think this looks good.
> 
> @DailyDreaming Do we actually want to drop the other Python versions from the main tests? Should we maybe keep 3.7 so we do the highest and lowest ostensibly supported versions?

Hmmm... maybe we could keep the old python tests, but reduce the time.  These tests have been taking 100+ minutes each, unfortunately, and I think for older versions of python, we should run a much shorter set of tests, and keep the extensive testing to the main python version we've pinned.  This limits the instances we can provision (and increases cost), for far too long per run I think.

Overall, we should probably re-organize the tests and try to reduce the time as they've gotten a little out of hand in runtime.

**Comment by adamnovak** [comment]
It looks like one of the CWL conformance tests timed out on Kubernetes:

https://ucsc-ci.com/databiosphere/toil/-/jobs/24890

```
Test 287 timed out: toil-cwl-runner --clean=always --logDebug --statusWait=10 --setEnv=SINGULARITY_DOCKER_HUB_MIRROR --batchSystem=kubernetes --outdir=/tmp/tmpj9i3nalu tests/conditionals/cond-wf-003_nojs.cwl tests/conditionals/test-false.yml
Pass through pattern with pickValue: first_non_null; 'when' is false'; no javascript
```

I don't think this is related to the PR being tested.

**Review by DailyDreaming — APPROVED** [review]
Merging this.  We can add the older python version tests back in a separate PR (in a reduced state).

**Pull request merged**
