### PR TITLE
Add decorator for flaky tests.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Current flaky issues that this adds retries for:
- #3511: SingleMachinePromisedRequirementsTest.testConcurrencyStatic
- #3478: MaxCoresSingleMachineBatchSystemTest.test
- #3461: testJobFileStore
- #3372: KubernetesBatchSystemTest.testRunJobs
- #3361: SingleMachineBatchSystemJobTest.testConcurrencyWithDisk
- #3127: jobServiceTest.JobServiceTest-testServiceParallelRecursive

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Add decorator for flaky tests.

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
@DailyDreaming: Looks like this is failing to launch a cluster because it has searched up AMIs it isn't allowed to use:

```
Traceback (most recent call last):
  File "/builds/databiosphere/toil/venv/bin/toil", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil')())
  File "/builds/databiosphere/toil/src/toil/utils/toilMain.py", line 30, in main
    module.main()
  File "/builds/databiosphere/toil/src/toil/utils/toilLaunchCluster.py", line 170, in main
    awsEc2ExtraSecurityGroupIds=options.awsEc2ExtraSecurityGroupIds)
  File "/builds/databiosphere/toil/src/toil/provisioners/aws/awsProvisioner.py", line 269, in launchCluster
    tags=leader_tags)
  File "/builds/databiosphere/toil/src/toil/lib/retry.py", line 256, in call
    return func(*args, **kwargs)
  File "/builds/databiosphere/toil/src/toil/lib/ec2.py", line 388, in create_instances
    return ec2_resource.create_instances(**prune(request))
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the RunInstances operation: Not authorized for images: [ami-02b46c73fed689d1c]
```

Probably not the fault of this PR, but it suggests we have a problem in `master` with the AMI finder.

**Review by adamnovak — APPROVED** [review]
This should hopefully reduce the number of unrelated PR failures we have due to these flaky tests.

@DailyDreaming Do you have issue numbers for actually fixing the flakiness of each of these tests? It might be good to mention them here or record them in comments near the decorated methods.

**Comment by adamnovak** [comment]
I think the Flatcar issue might just be that we were running tests at the same time as they were pushing an update. That AMI it couldn't use is now the current production AMI and seems to work fine, and March 25 when the tests ran was also the release date of that Flatcar version.

**Comment by DailyDreaming** [comment]
@adamnovak Added, thanks for the review!

**Pull request merged**
