### PR TITLE
Issue/3960 scatter outputs should not clash (#3)

### PR DESCRIPTION
**Pull request by kannon92**
## Changelog Entry

If you use scatter and collect files, you can now correctly detect duplicates.  Follow the same behavior that cwltool does.

Fix https://github.com/DataBiosphere/toil/issues/3960

## Reviewer Checklist

 * [x] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [x] Read through the code changes. Make sure that it doesn't have:
    * [x] Addition of trailing whitespace.
    * [x] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [x] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [x] New functions or classes without informative docstrings.
    * [x] Changes to semantics not reflected in the relevant docstrings.
    * [x] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [x] New features without tests.
* [x] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [x] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by adamnovak — APPROVED** [review]
The inline docstring is a little weird, but I think this is going to work. I'll pull it in for testing to see if it passes.

**Comment by adamnovak** [comment]
OK I pulled this in to https://github.com/DataBiosphere/toil/tree/issues/3960-scatter-outputs-should-not-clash

**Comment by mr-c** [comment]
@adamnovak I've updated https://github.com/DataBiosphere/toil/tree/issues/3960-scatter-outputs-should-not-clash with https://github.com/DataBiosphere/toil/pull/3968/commits/367db18b43e0d2c9a1e043ee919253acdbb9fb0e

**Comment by kannon92** [comment]
Anyone know what the reason for the test failure is?  I don't think its the test I added but I am having a hard time deducing what the actual failure is.

**Comment by mr-c** [comment]
> Anyone know what the reason for the test failure is? I don't think its the test I added but I am having a hard time deducing what the actual failure is.

`src/toil/test/cwl/cwlTest.py::CWLv12Test::test_run_conformance_with_in_place_update` failed, specifically 

```
Test 237 failed: toil-cwl-runner --clean=always --logDebug --statusWait=10 --disableCaching --bypass-file-store --setEnv=SINGULARITY_DOCKER_HUB_MIRROR --outdir=/tmp/tmpa0_28gnz --quiet tests/inpdir_update_wf.cwl tests/empty.json
inplace update has side effect on directory content
Compare failure expected: {
    "a": [
        {
            "basename": "blurb",
            "class": "File",
            "location": "blurb"
        }
    ],
    "b": [
        {
            "basename": "blurb",
            "class": "File",
            "location": "blurb"
        }
    ]
}
got: {
    "a": [
        {
            "basename": "blurb",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "location": "file:///tmp/tmpa0_28gnz/blurb",
            "nameext": "",
            "nameroot": "blurb",
            "size": 0
        }
    ],
    "b": [
        {
            "basename": "blurb",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "location": "file:///tmp/tmpa0_28gnz/blurb_2",
            "nameext": "",
            "nameroot": "blurb",
            "size": 0
        }
    ]
}
caused by: failed comparison for key 'b': expected: [
    {
        "basename": "blurb",
        "class": "File",
        "location": "blurb"
    }
]
got: [
    {
        "basename": "blurb",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File",
        "location": "file:///tmp/tmpa0_28gnz/blurb_2",
        "nameext": "",
        "nameroot": "blurb",
        "size": 0
    }
]
caused by: expected: {
    "basename": "blurb",
    "class": "File",
    "location": "blurb"
}
got: {
    "basename": "blurb",
    "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "class": "File",
    "location": "file:///tmp/tmpa0_28gnz/blurb_2",
    "nameext": "",
    "nameroot": "blurb",
    "size": 0
}
caused by: file:///tmp/tmpa0_28gnz/blurb_2 does not end with blurb
```

**Comment by kannon92** [comment]
> src/toil/test/cwl/cwlTest.py::CWLv12Test::test_run_conformance_with_in_place_update

Thank you @mr-c.  Can you explain a bit about these tests?  It looks like your logs make it seem like this is a real test failure but I don't see these tests in toil.  

Is toil pulling in conformance tests from another repo?  And where is the expected value coming from?

It looks like this test is catching the erroneous behavior with the same file repeated rather than different files.  I'm running these tests locally so I'll see what the fix is.

**Comment by kannon92** [comment]
Alright.  I looked into this but I am confused at what this test is doing.  

```
#!/usr/bin/env cwl-runner
class: Workflow
cwlVersion: v1.2
inputs: []
requirements:
  InlineJavascriptRequirement: {}
outputs:
  a:
    type: File[]
    outputSource: step3/d1out
  b:
    type: File[]
    outputSource: step3/d2out
steps:
  step1:
    in:
      dirname: {default: step1dir}
    out: [out]
    run: mkdir.cwl
  step2:
    in:
      r: step1/out
    out: [out]
    run: updatedir_inplace.cwl
  step3:
    in:
      d1: step1/out
      d2: step2/out
    out: [d1out, d2out]
    run:
      class: ExpressionTool
      inputs:
        d1:
          type: Directory
          loadListing: shallow_listing
        d2:
          type: Directory
          loadListing: shallow_listing
      outputs:
        d1out: File[]
        d2out: File[]
      expression: "$({d1out: inputs.d1.listing, d2out: inputs.d2.listing})"

```

So it looks like both a and b outputs point to the same file.  My code detects a conflict and uses blah_2 for one of them.  

I think I need to make this code smarter so that if the File[] corresponds to an separate output object, I shouldn't detect a conflict.  

But is it intended that each step should generate the same file and we want to use the same file path for each?  Both cwltool and old toil-cwl-runner have the same behavior so I believe I introduced a regression.

**Comment by mr-c** [comment]
@kannon92 Here's a hint https://www.commonwl.org/v1.2/CommandLineTool.html#InplaceUpdateRequirement

**Comment by mr-c** [comment]
popular with Radio Astronomers who have really big datasets they prefer to modify in place; they are users of `toil-cwl-runner` so it is important we don't break this feature

**Comment by kannon92** [comment]
So this is intended?

```
[2021-12-22T14:33:31-0500] [MainThread] [D] [toil.cwl.cwltoil] Staging output: MapperEnt(resolved='/private/var/folders/8_/4wtcxlwx4yd3p3jkyxvbw8gr0000gp/T/tmpakohlvys/step1dir/blurb', target='/Users/kevinhannon/Work/GIT/toil-polusai/blurb', type='File', staged=True)
[2021-12-22T14:33:31-0500] [MainThread] [D] [toil.cwl.cwltoil] Staging output: MapperEnt(resolved='/private/var/folders/8_/4wtcxlwx4yd3p3jkyxvbw8gr0000gp/T/tmpw8vg_z7p/inp/blurb', target='/Users/kevinhannon/Work/GIT/toil-polusai/blurb', type='File', staged=True)
{
    "a": [
        {
            "class": "File",
            "location": "file:///Users/kevinhannon/Work/GIT/toil-polusai/blurb",
            "basename": "blurb",
            "nameroot": "blurb",
            "nameext": "",
            "size": 0,
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709"
        }
    ],
    "b": [
        {
            "class": "File",
            "location": "file:///Users/kevinhannon/Work/GIT/toil-polusai/blurb",
            "basename": "blurb",
            "size": 0,
            "nameroot": "blurb",
            "nameext": "",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709"
        }
    ]
}
```

Looks like in the tool run, the files are placed into separate locations in the container but we end up mapping them to the same location.  Currently, blurb has no data in it but wouldn't tool 2 overwrite whatever tool 1 wrote?

**Comment by mr-c** [comment]
>  Currently, blurb has no data in it but wouldn't tool 2 overwrite whatever tool 1 wrote?

Correct

**Comment by kannon92** [comment]
Thanks for your help @mr-c .  I will look into ways to fix this test.

**Comment by kannon92** [comment]
Alright.  I pushed a change that fixes the failing test.  I notice that cwltool has the following code: https://github.com/common-workflow-language/cwltool/blob/main/cwltool/process.py#L388

I did some research and I notice that the missing visit_class function in toil maps the files in that test to the same location so that the pathmapper knows to not have two copies.  

I don't completely understand all the different ways cwltool and toil handle path mappings.

**Comment by mr-c** [comment]
@adamnovak I've updated https://github.com/DataBiosphere/toil/tree/issues/3960-scatter-outputs-should-not-clash with https://github.com/DataBiosphere/toil/pull/3968/commits/eea059b1a5d6fdaaadc184ae9a580f3f2687084b

**Pull request merged**
