### PR TITLE
Support per-task preemptibility in CWL

### LINKED ISSUE #4258: Support the `arv:UsePreemptible` hint in CWL to allow CWL tasks on spot instances
Is it possible to specify in a multi-stage workflow, consisted of multiple tasks (e.g. alignment, sort vcf, index vcf, etc), specific task to be using on-demand (non-preemptable) nodes, while others can use preemptable. This is because for very long running workflow, there are some steps that will for sure take 15+ hours to finish and because it is not using spot instances, no matter how many retries, it'll very likely be killed if using spot. But I don't want the entire workflow to be using on-demand instances, as there are many other smaller tasks fully suitable for using spot.

From the arguments (`defaultPreemptable`, `nodeTypes`, `preemptableCompensation`), they only control at the entire job level, and not to the individual task. It was mentioned in [documentation](https://toil.readthedocs.io/en/releases-3.6.x/running/cloud.html) "While individual jobs can each explicitly specify whether or not they should be run on preemptable nodes via the boolean preemptable resource requirement, ...", was this referring to specify `preemptable` in `ResourceRequirement` in the CWL? This would result in the error `invalid field preemptable, expected one of: 'class', 'coresMin', 'coresMax', 'ramMin', 'ramMax', 'tmpdirMin', 'tmpdirMax', 'outdirMin', 'outdirMax'`, as `preemptable` isn't one of the options.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1235)
┆friendlyId: TOIL-1235

### PR DESCRIPTION
**Pull request by adamnovak**
This will fix #4258 by allowing you to specify preemptibility per-task in CWL, like you can in WDL.

Unfortunately [the Arvados schema we are trying to support](https://github.com/arvados/arvados/blob/48a0d575e6de34bcda91c489e4aa98df291a8cca/sdk/cwl/arvados_cwl/arv-cwl-schema-v1.1.yml#L345) only allows literal `boolean` values, and not parameter references/expressions, and I couldn't figure out how to get `cwltool` to evaluate the expressions in hints, so I'm not supporting expressions for preemptibility (yet?).

I've added some tests for parsing/validation, but I couldn't figure out how to add a good unit test for the preemptibility flag *actually* making it to the Toil backend and having an effect, since it doesn't matter single-machine and I don't want to spin up a cluster on CI to test this.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * `toil-cwl-runner` now supports the `http://arvados.org/cwl#UsePreemptible` AKA `arv:UsePreemptible` hint

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
This had a test end up in an ERROR state due to a failing teardown, because AWS refused to let us delete a bucket:
```
==================================== ERRORS ====================================
_ ERROR at teardown of EncryptedAWSJobStoreTest.test_testImportSharedFile__otherCls_filejobstoretest _
[gw3] linux -- Python 3.9.16 /builds/databiosphere/toil/venv/bin/python
Traceback (most recent call last):
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/runner.py", line 182, in pytest_runtest_teardown
    item.session._setupstate.teardown_exact(nextitem)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/runner.py", line 537, in teardown_exact
    raise exceptions[0]
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/runner.py", line 526, in teardown_exact
    fin()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/fixtures.py", line 1031, in finish
    raise exc
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/fixtures.py", line 1024, in finish
    func()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    next(it)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/python.py", line 575, in xunit_setup_module_fixture
    _call_with_optional_argument(teardown_module, request.module)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/_pytest/python.py", line 776, in _call_with_optional_argument
    func()
  File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 70, in tearDownModule
    AbstractJobStoreTest.Test.cleanUpExternalStores()
  File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 642, in cleanUpExternalStores
    test._cleanUpExternalStore(store)
  File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 1484, in _cleanUpExternalStore
    bucket.delete()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the DeleteBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
```

We should figure out a way to make AWS errors in teardown not fail a test.

**Comment by adamnovak** [comment]
@DailyDreaming I think this is ready for review. Do you want to look at it?

**Review by DailyDreaming — APPROVED** [review]
> Unfortunately [the Arvados schema we are trying to support](https://github.com/arvados/arvados/blob/48a0d575e6de34bcda91c489e4aa98df291a8cca/sdk/cwl/arvados_cwl/arv-cwl-schema-v1.1.yml#L345) only allows literal boolean values, and not parameter references/expressions, and I couldn't figure out how to get cwltool to evaluate the expressions in hints, so I'm not supporting expressions for preemptibility (yet?).

That sounds fine to me.

> I've added some tests for parsing/validation, but I couldn't figure out how to add a good unit test for the preemptibility flag actually making it to the Toil backend and having an effect, since it doesn't matter single-machine and I don't want to spin up a cluster on CI to test this.

I think that that's fine.  The test looks good to me and spinning up something might be overkill with all of our other tests.

PR overall looks great, thanks for adding this.

**Review by mr-c — APPROVED** [review]
> Unfortunately [the Arvados schema we are trying to support](https://github.com/arvados/arvados/blob/48a0d575e6de34bcda91c489e4aa98df291a8cca/sdk/cwl/arvados_cwl/arv-cwl-schema-v1.1.yml#L345) only allows literal `boolean` values, and not parameter references/expressions, and I couldn't figure out how to get `cwltool` to evaluate the expressions in hints, so I'm not supporting expressions for preemptibility (yet?).

To me, it seems reasonable to support expressions there.

[I've asked @tetron about this](https://matrix.to/#/!iCGZYZrhxQUZbnMoxM:gitter.im/$NXKqRw5krlxyHsfrbOt0YzkY1dpz-jDECuqMjt2frls)

If Peter agrees, then I will submit an PR later to add the necessary schema extension to enable this. It will also allow use of `arv:UsePreemptible` under `requirements`, not just `hints`.

**Pull request merged**
