### PR TITLE
cwl: use the latest commit from the proposed CWL v1.2.1 branch

### PR DESCRIPTION
**Pull request by mr-c**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * CWL conformance testing: use the latest commit from the proposed CWL v1.2.1 branch

Related to https://github.com/DataBiosphere/toil/issues/4564

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by DailyDreaming — APPROVED** [review]
LGTM.  Hopefully tests pass.

**Comment by mr-c** [comment]
Eep: 368 tests passed, 4 failures, 2 unsupported features

**Comment by mr-c** [comment]
This PR passes the CWL conformance tests for me locally. Some sort of timeout issue on the CI cluster?

**Comment by mr-c** [comment]
@adamnovak How do I trigger running the CWL conformance tests against this branch now that they are removed from the regular CI?

**Comment by adamnovak** [comment]
Sorry, I didn't get my page. I think we have to do something like what I'm doing in #4636 to make the CWL conformance CI tests run when CWL stuff is changed. Or maybe make the .gitlab-ci.yml make "manual" versions of the relevant tests that we can trigger?

It does look like this PR broke the conformance tests, since we don't actually yet pass some of the new tests. #4570 is supposed to fix that but until then I think I have to back this out in #4636.

**Pull request merged**
