### PR TITLE
Use environment variable to set parallel partition name

### PR DESCRIPTION
**Pull request by gcapes**
Previously, setting `--partition=multicore` in TOIL_SLURM_ARGS
was trying to force serial tasks into the parallel partition,
which were failing to run due to requesting a single core.

I was running a CWL workflow with multiple steps, 
some of which were serial, and some parallel.
TOIL was not sending jobs to the appropriate queue -
if `--partition=serial` was set in `TOIL_SLURM_ARGS`,
or no partition was set, serial steps would run, but not
parallel.
If `--partition=multicore` was set in `TOIL_SLURM_ARGS`,
serial steps would not run, as this option applies to
all steps.

The proposed fix uses an environment variable to store 
the name of the parallel partition, and add this to the
sbatch command for tasks requiring more than 1 core.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * PR submitter writes their recommendation for a changelog entry here

## Reviewer Checklist

 * [x] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [x] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [x] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Thanks @gcapes!

Can you also document this in https://github.com/DataBiosphere/toil/blob/master/docs/appendices/environment_vars.rst & https://github.com/DataBiosphere/toil/blob/master/docs/developingWorkflows/toilAPIBatchsystem.rst ?

**Comment by mr-c** [comment]
@gcapes is there a way to determine which SLURM queues are only for multicore jobs? Likewise for queues only enabled for single core jobs?

**Comment by gcapes** [comment]
I don't know enough about SLURM to answer that @mr-c. I understand that the partition (queue) names are not standardised and so vary between HPC systems.

**Comment by mr-c** [comment]
> I don't know enough about SLURM to answer that @mr-c. I understand that the partition (queue) names are not standardised and so vary between HPC systems.

No worries. Would be neat if there is a way to query queue characteristics.

**Comment by gcapes** [comment]
I guess it would be here if it were possible, but it doesn't look to be: https://slurm.schedmd.com/sinfo.html

**Comment by mr-c** [comment]
Is `MaxCPUsPerNode` set for your `serial` partition? See ` --Format`

(None of this information is required for this PR. I am curious if a future feature can be developed.)

**Comment by gcapes** [comment]
Is this what you're asking?
```
$ sinfo -O MaxCPUsPerNode
MAX_CPUS_PER_NODE   
UNLIMITED           
```

**Comment by gcapes** [comment]
I can't see how to 'respond' to the request for changes. But they're in https://github.com/DataBiosphere/toil/pull/4096/commits/b9aa7d71843c87341423b9490fcbad2f0d5e006b

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Thank you @gcapes !

**Pull request merged**
