### PR TITLE
Prohibit schema-salad 8.3 which thinks CWL versions need to be filenames

### LINKED ISSUE #4168: CI failures due to schema-salad
In cases like https://ucsc-ci.com/databiosphere/toil/-/jobs/19601 I was seeing CI tests fail because `schema-salad` was deciding that CWL versions like `v1.2` really ought to be filenames:

```
_________________ CWLWorkflowTest.test_download_directory_file _________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 374, in test_download_directory_file
    self.download_directory("download_directory_file.json", self._tester)
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 281, in download_directory
    tester_fn(
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 228, in _tester
    cwltoil.main(main_args, stdout=st)
  File "/builds/databiosphere/toil/src/toil/cwl/cwltoil.py", line 3499, in main
    loading_context, uri = cwltool.load_tool.resolve_and_validate_document(
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/cwltool/load_tool.py", line 384, in resolve_and_validate_document
    document_loader.resolve_all(workflowobj, fileuri)
  File "schema_salad/ref_resolver.py", line 965, in resolve_all
  File "schema_salad/ref_resolver.py", line 1197, in validate_links
  File "schema_salad/ref_resolver.py", line 1124, in validate_links
  File "schema_salad/ref_resolver.py", line 1062, in validate_link
schema_salad.exceptions.ValidationException: src/toil/test/cwl/download_directory.cwl:1:1: Field `cwlVersion` contains undefined reference to
                                              `file:///builds/databiosphere/toil/src/toil/test/cwl/v1.2`
```

I was having trouble reproducing this on my machine, and I tracked it down to being related to the `schema-salad` version. Using version `8.3.20220518163624` or later causes the bug to appear, while using version `8.2.20220204150214` or earlier works fine.

I'm going to see if I can pin us to the older, working versions.

@mr-c Do you have any idea how we could track down what exactly the problem between us and `schema-salad` is here? Have we just been using it or `cwltool` wrong in a way that could cause it to try and validate the CWL version fields as if they were supposed to be paths to files that exist?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1198)
┆friendlyId: TOIL-1198

### PR DESCRIPTION
**Pull request by adamnovak**
This should hackily fix #4168 by restricting us to versions of schema-salad that seem to work. 

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * `schema-salad` is restricted to version 8.2 or below which can validate CWL version strings properly and not as files (#4168)

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by mr-c** [comment]
@adamnovak Sorry about this regression; I've yanked that release, so maybe you don't need this PR anymore?

https://pypi.org/project/schema-salad/8.3.20220721194857/

https://github.com/common-workflow-language/schema_salad/issues/575

**Comment by adamnovak** [comment]
@mr-c It's not just `8.3.20220721194857`; I observed the problem all the way back to the first 8.3 release, `8.3.20220518163624`, at least when I tried it. So I don't think yanking just one version is going to fix it, and I'm not sure it's a good idea to yank everything just because Toil breaks; I haven't tested `cwltool` alone.

**Comment by adamnovak** [comment]
This PR failed the batch system tests because the TES batch system never managed to run its tasks. I don't think this PR has anything to do with TES, so I'm trying to rerun the test. If it succeeds, we should mark the TES tests as flaky or otherwise fix them. Or maybe drop them since TES support in Toil has no users that I know of.

**Comment by mr-c** [comment]
> So I don't think yanking just one version is going to fix it, and I'm not sure it's a good idea to yank everything just because Toil breaks; I haven't tested `cwltool` alone.

We did test with `cwltool` and we got the same error, hence the yank

**Comment by adamnovak** [comment]
I'm going to merge this without a real review since we need it to fix CI.

**Pull request merged**
