### PR TITLE
[WIP] record the maximum memory used by LSF jobs

### PR DESCRIPTION
**Pull request by mr-c**
- [ ] merge this `bhist` call with the `bjobs` calls below?
- [ ] parse the "human friendly" memory value into an int/long?
- [ ] refactor to return the result code & the memory used together?

### CODE REVIEW

**Comment by mr-c** [comment]
@drkennetz would you have any interest in taking over this PR?

**Comment by drkennetz** [comment]
@mr-c yeah I'll take it over! should be easy enough. Max mem can be determined from bjobs -l which I think is already called somewhere. Is there any value in actually returning the Max Mem used, rather than just logging it? I bring that up because this would have to be reflected in leader.py and job.py, which I think would result in some ugly and perhaps unnecessary isintance checks until this change was synced across all schedulers.

**Comment by mr-c** [comment]
@drkennetz you can log it for now; some day we will want to return it for provenance recording ; thanks!

**Comment by drkennetz** [comment]
@mr-c I've started work on this yesterday. I'll probably open a new PR when ready.

**Pull request closed without merging**
