### PR TITLE
Fix s3 import for cwltoil (resolves #2234)

### LINKED ISSUE #2234: s3 support for toil-cwl-runner?
The quickstart guide states:
>When running a CWL workflow on AWS, input files can be provided either on the local file system or in S3 buckets using s3:// URI references. Final output files will be copied to the local file system of the leader node."

However, I consistently get the error at this point in the code:
`"file." % (knownfile, self.pathmapper.mapper(knownfile)[0]))`
reporting:
`WorkflowException: Input file https://s3.amazonaws.com/<bucket>/<file> (at //s3.amazonaws.com/<bucket>/<file>) not found or is not a regular file.`

or, if I use the `s3://` URI system I get:
`WorkflowException: Input file s3://<bucket>/<file> (at //<bucket>/<file>) not found or is not a regular file.`

where `<bucket>` and `<file>` are obviously filled in with my specific bucket and file.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-103)
┆Issue Number: TOIL-103

### PR DESCRIPTION
**Pull request by nikhil**
The jobstore should be able to handle import from different file schemes

### CODE REVIEW

**Comment by nikhil** [comment]
I wanted to add more tests, but I can't guarantee any file I upload (on s3 for example) will be available permanently for testing. Does toil have any cloud files that can be used for testing?

**Comment by nikhil** [comment]
@mr-c I added some tests for S3, http, and https.

**Comment by DailyDreaming** [comment]
@nikhil Sorry this has taken a bit.  Will test and likely merge in the morning.  LGTM.

**Comment by mr-c** [comment]
Thank you @nikhil for the tests!

**Comment by DailyDreaming** [comment]
Tests are failing with what looks like a permissions problem on the bucket.  I just need to grant the runner permissions, though it should be publicly downloadable I believe.  Will look into it a bit more.  For reference:
```
_____________________________ CWLTest.test_run_s3 ______________________________
Traceback (most recent call last):
  File "/home/ubuntu/toil/src/toil/test/cwl/cwlTest.py", line 111, in test_run_s3
    self.download('download_s3.json', self._tester)
  File "/home/ubuntu/toil/src/toil/test/cwl/cwlTest.py", line 99, in download
    self._expected_download_output(self.outDir))
  File "/home/ubuntu/toil/src/toil/test/cwl/cwlTest.py", line 71, in _tester
    cwltoil.main(main_args, stdout=st)
  File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 1251, in main
    import_files(initialized_job_order)
  File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 1229, in import_files
    skip_broken=True))
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/cwltool/pathmapper.py", line 47, in adjustFileObjs
    visit_class(rec, ("File",), op)
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/cwltool/utils.py", line 210, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/cwltool/utils.py", line 208, in visit_class
    op(rec)
  File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 365, in uploadFile
    uploadfunc, fileindex, existing, uf["location"])
  File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 337, in write_file
    index[x] = "toilfs:" + writeFunc(rp)
  File "/home/ubuntu/toil/src/toil/common.py", line 953, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/home/ubuntu/toil/src/toil/jobStores/abstractJobStore.py", line 299, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/home/ubuntu/toil/src/toil/jobStores/fileJobStore.py", line 272, in _importFile
    sharedFileName=sharedFileName)
  File "/home/ubuntu/toil/src/toil/jobStores/abstractJobStore.py", line 320, in _importFile
    otherCls._readFromUrl(url, writable)
  File "/home/ubuntu/toil/src/toil/jobStores/aws/jobStore.py", line 435, in _readFromUrl
    srcKey = cls._getKeyForUrl(url, existing=True)
  File "/home/ubuntu/toil/src/toil/jobStores/aws/jobStore.py", line 476, in _getKeyForUrl
    with closing(boto.connect_s3()) as s3:
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/home/ubuntu/toil/venv/lib/python3.6/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
----------------------------- Captured stderr call -----------------------------
INFO:cwltool:Resolved '/home/ubuntu/toil/src/toil/test/cwl/download.cwl' to 'file:///home/ubuntu/toil/src/toil/test/cwl/download.cwl'
URI prefix 's3' of 's3://toil-datasets/wdl_templates.zip' not recognized, are you missing a $namespaces section?
WARNING:salad:URI prefix 's3' of 's3://toil-datasets/wdl_templates.zip' not recognized, are you missing a $namespaces section?
ERROR:cwltool:Got exception 'No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials' while copying 's3://toil-datasets/wdl_templates.zip'
------------------------------ Captured log call -------------------------------
load_tool.py                98 INFO     Resolved '/home/ubuntu/toil/src/toil/test/cwl/download.cwl' to 'file:///home/ubuntu/toil/src/toil/test/cwl/download.cwl'
ref_resolver.py            352 WARNING  URI prefix 's3' of 's3://toil-datasets/wdl_templates.zip' not recognized, are you missing a $namespaces section?
cwltoil.py                 340 ERROR    Got exception 'No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials' while copying 's3://toil-datasets/wdl_templates.zip'
```

**Comment by nikhil** [comment]
I think it might be because I have the file `~/.boto` present

**Comment by nikhil** [comment]
Ignore my previous comment. It still works for me without the ~/boto file. I am using boto version 2.48.0 on Python 2.7 FWIW

**Comment by nikhil** [comment]
Just wondering if there was an update to this, I was not able to replicate the issue above.

**Comment by arostamianfar** [comment]
@adamnovak @DailyDreaming @nikhil I got the same error independently and I think it's caused by commit https://github.com/DataBiosphere/toil/commit/eab035bfc4abf205e937aa4b85caf0d666f26842 (the commit just before this one works).
Not yet sure what the root cause is though. Adam, do you have any ideas?

**Comment by adamnovak** [comment]
Hm. @arostamianfar It could be that my replacing the Boto2 credentials provider with a shim over Boto3 is causing the credentials, at least in your environment, to not actually be loaded, somehow.

Do you have your credentials in `~/.aws/credentials` (where Boto3 wants them to be) instead of/in addition to the Boto2 `~/.boto` file? If you have both files, do the credentials agree? The `~/.aws/credentials` file will now take precedence, after my changes, I believe.

If you only have the one file, is your `~/.boto` file well-formed (and not malformed in a way that is legible to Boto2 and not Boto3)? 

Can other tools that use Boto3, like the `aws` command line utility, authenticate successfully?

It looks like @nikhil's errors predate my revising of the Boto authentication logic, so I doubt that the cause of your issue is quite the same.

**Comment by arostamianfar** [comment]
@adamnovak Thanks for the quick reply! I was setting the credentials through environment variables and while it was found by boto, it was being ignored by Toil. I sent https://github.com/DataBiosphere/toil/pull/2549 that fixed it. Please take a look and let me know if it's the right approach!
RE timing: interesting! The error was indeed seen before that commit, so it's likely a different issue. Sorry for the false alarm.

**Pull request merged**
