### PR TITLE
Fix failing Google jobstore tests

### LINKED ISSUE #3419: Fix failing Google job store tests
There are a couple tests failing for Google job store, due to String/Byte type inconsistencies between Python2/3 related to #3388. 

**Error:** 
```
Traceback (most recent call last):
   File "/builds/databiosphere/toil/src/toil/test/__init__.py", line 663, in fx
     return generalMethod(self, **prms)
   File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 649, in testImportExportFile
     srcUrl, srcMd5 = other._prepareTestFile(store, size)
   File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 1171, in _prepareTestFile
     GoogleJobStore._writeToUrl(StringIO(contents), urlparse.urlparse(url))
   File "/builds/databiosphere/toil/src/toil/jobStores/googleJobStore.py", line 361, in _writeToUrl
     blob.upload_from_file(readable)
   File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 946, in upload_from_file
     client, file_obj, content_type, size, num_retries)
   File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 867, in _do_upload
     client, stream, content_type, size, num_retries)
   File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 700, in _do_multipart_upload
     transport, data, object_metadata, content_type)
   File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 137, in transmit
     data, metadata, content_type
   File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 292, in _prepare_request
     raise TypeError(u"`data` must be bytes, received", type(data))
 TypeError: ('`data` must be bytes, received', <class 'str'>)
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-779)
┆Issue Number: TOIL-779

### PR DESCRIPTION
**Pull request by jonathanxu18**
Should fix #3419.

### CODE REVIEW

**Review by DailyDreaming — APPROVED** [review]
This looks good to me.

**Comment by DailyDreaming** [comment]
@jonathanxu18 The same changes appear to be in #3412 .  We should probably wait for and only merge that one since it's actually running the Google jobstore tests.  Assuming tests pass there though, that looks good to go.

**Review by DailyDreaming — APPROVED** [review]
Approving this just to add some minor type hinting.

**Comment by jonathanxu18** [comment]
> Approving this just to add the type hinting from the rebase.

Got it, sorry about missing that part.

**Pull request merged**
