### PR TITLE
Use forked pymesos and http-parser dependencies.

### PR DESCRIPTION
**Pull request by DailyDreaming**
Hopefully these work, will just wait on tests to confirm.

### CODE REVIEW

**Comment by DailyDreaming** [comment]
@adamnovak @diekhans Looks like a C code error, any ideas?

```
     Running setup.py install for zkpython: started
    ERROR: Command errored out with exit status 1:
     command: /builds/databiosphere/toil/venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-exhndyre/zkpython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-exhndyre/zkpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vn6e9grk/install-record.txt --single-version-externally-managed --compile --install-headers /builds/databiosphere/toil/venv/include/site/python3.6/zkpython
         cwd: /tmp/pip-install-exhndyre/zkpython/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'zookeeper' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/c-client-src -I/usr/local/include/c-client-src -I/usr/include/zookeeper -I/usr/local/include/zookeeper -I/usr/include/python3.6m -I/builds/databiosphere/toil/venv/include/python3.6m -c zookeeper.c -o build/temp.linux-x86_64-3.6/zookeeper.o
    zookeeper.c:20:10: fatal error: zookeeper.h: No such file or directory
     #include <zookeeper.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
    Running setup.py install for zkpython: finished with status 'error'
ERROR: Command errored out with exit status 1: /builds/databiosphere/toil/venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-exhndyre/zkpython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-exhndyre/zkpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vn6e9grk/install-record.txt --single-version-externally-managed --compile --install-headers /builds/databiosphere/toil/venv/include/site/python3.6/zkpython Check the logs for full command output.
Makefile:97: recipe for target 'develop' failed
```

**Comment by DailyDreaming** [comment]
Two interesting things happened.  One is that toil ran out of s3 buckets, so it's probably not cleaning up and we should do that.

@adamnovak And this:
```
_____________________ KubernetesBatchSystemTest.testSetEnv _____________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/batchSystems/batchSystemTest.py", line 217, in testSetEnv
    jobID, exitStatus, wallTime = jobUpdateInfo.jobID, jobUpdateInfo.exitStatus, jobUpdateInfo.wallTime
AttributeError: 'NoneType' object has no attribute 'jobID'
```

Link: https://ucsc-ci.com/databiosphere/toil/pipelines/3626

It's getting late so I'll get back to this tomorrow.

**Comment by adamnovak** [comment]
I think that error from testing the Kubernetes batch system is just what you get from that test if you send in a job and it doesn't run within 1000 seconds. It could be cluster load again.

I'll try to clean up the left-behind buckets. I'm not sure where we're forgetting to destroy them. Maybe it happens when we cancel tests?

I don't actually have access to the console for the Toil account yet, but Kubernetes can get in, so I'll try going through a pod.

**Comment by adamnovak** [comment]
OK @DailyDreaming I have console access now.

It looks like we do indeed have loads and loads of Toil test buckets, but about 40 of them were created between 2020-04-02T00:27:51.000Z and 2020-04-02T00:30:33.000Z (around 5:30 PM yesterday) with the last one before that being from March 25th. So I think it's not so much a reliable, persistent bucket leak as something going terribly wrong in a particular test run. It could be all the checksumming stuff I was working on yesterday; maybe that super didn't work and the AWS batch system started reliably crashing in that branch, and leaving things behind.

**Comment by adamnovak** [comment]
I'm rerunning the failed tests here now that I have cleaned up a bunch of abandoned jobstores. Hopefully between that and having another bite at the Kubernetes apple, they pass.

**Comment by adamnovak** [comment]
OK, I suspect the real problem here with getting Kubernetes jobs to run from 3.7 is that we only build the appliance for 3.6. The 3.7 leader is going to ask for a `-py3.7` version of the appliance which doesn't exist, and this would manifest as Kubernetes jobs never actually starting.

We maybe should add support for working out when the image doesn't actually exist to the Kubernetes batch system, so it can tell us if/when this happens. But the actual fix is to make sure to build a 3.7 appliance, I guess alongside the 3.6 one.

**Comment by adamnovak** [comment]
Yep, here's what Kubernetes thinks of the 3.7 jobs:

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  50s                default-scheduler  Successfully assigned toil/root-toil-448f5946-a1de-4802-be3f-40e4c7b2ab80-0-jzwm4 to k3.kube
  Normal   BackOff    19s (x2 over 49s)  kubelet, k3.kube   Back-off pulling image "quay.io/ucsc_cgl/toil:4.0.0a1-ed1226bcdab18b7431bceeb818ecc6684deb84cf-py3.7"
  Warning  Failed     19s (x2 over 49s)  kubelet, k3.kube   Error: ImagePullBackOff
  Normal   Pulling    8s (x3 over 50s)   kubelet, k3.kube   Pulling image "quay.io/ucsc_cgl/toil:4.0.0a1-ed1226bcdab18b7431bceeb818ecc6684deb84cf-py3.7"
  Warning  Failed     7s (x3 over 49s)   kubelet, k3.kube   Failed to pull image "quay.io/ucsc_cgl/toil:4.0.0a1-ed1226bcdab18b7431bceeb818ecc6684deb84cf-py3.7": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/ucsc_cgl/toil:4.0.0a1-ed1226bcdab18b7431bceeb818ecc6684deb84cf-py3.7 not found
  Warning  Failed     7s (x3 over 49s)   kubelet, k3.kube   Error: ErrImagePul
```

**Comment by adamnovak** [comment]
@DailyDreaming Is this the last thing we're waiting on for the 4.0 release? And are you going to do the release or should I figure it out?

**Comment by DailyDreaming** [comment]
@adamnovak This is the last thing.  I'll merge this since tests have passed and then modify the tests in a follow-up PR.

**Pull request merged**
