### PR TITLE
upgrade cwltool to cwl v1.2.0-dev4

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
hey @adamnovak ; any advice about https://ucsc-ci.com/databiosphere/toil/-/jobs/55616 ?

**Comment by mr-c** [comment]
@DailyDreaming I merged your PR, but the `py3[678]_main` gitlab CI jobs are still failing for reasons that escape me: https://ucsc-ci.com/databiosphere/toil/pipelines/4509

**Comment by DailyDreaming** [comment]
@mr-c Looks like the builder had a new arg added: https://github.com/common-workflow-language/cwltool/blob/main/cwltool/builder.py#L175

I added a fix.  Running the tests now, hopefully no other items turn up.

**Comment by DailyDreaming** [comment]
@mr-c I usually have to go to the raw logs, search for "= fail", which finds the section header: "=================================== FAILURES ===================================", and then once I have the names of the tests under that, I can search back for them to get a more complete log.

**Comment by mr-c** [comment]
@DailyDreaming Thanks for the tip! Maybe you could add that to https://toil.readthedocs.io/en/master/contributing/contributing.html#contributing :-)

**Comment by DailyDreaming** [comment]
@mr-c Ha, alright, I'll flag you for review then when I make it.  Got to run right now, but later on today or in the morning!

**Comment by mr-c** [comment]
Woohoo, thank you @dailydreaming!

**Pull request merged**
