### PR TITLE
Issues/2401 hardcopying and toil status (Resolves #2401)

### LINKED ISSUE #2401: Hard copying files into fileJobstore and restoring Toil Status
Parts of #2335 were reverted to fix larger issues with Toil. Those reverted bits should be restored after fixing its issues.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-360)
┆Issue Number: TOIL-360

### PR DESCRIPTION
**Pull request by bencvdb**
This PR addresses the issues with #2335 that caused parts of it to be reverted: the leader was leaving local copies of files used to determine workflow status. These files were left because CWL tool uses symlinking and deleting them after importing them into the jobstore would cause them to break. This has been addressed by adding support for hard copying symlinked files into the jobstore. 

Finally, the unit tests for the `ToilStatus.getStatus()` and `ToilStatus.getPIDStatus()` now use the jobstore created in setup, and removed in teardown, instead of creating one for each test. This prevents files created in `toil.sort` from being left behind.

### CODE REVIEW

**Comment by bencvdb** [comment]
Jenkins, test this please.

**Comment by bencvdb** [comment]
Jenkins, test this please.

**Comment by bencvdb** [comment]
Different set of failures second time around...
http://jenkins.cgcloud.info/job/toil-pull-requests/4577/

**Comment by DailyDreaming** [comment]
Looks good to me!

**Pull request merged**
