### PR TITLE
Prevent zombie process when mesos batch system can't create new thread

### PR DESCRIPTION
**Pull request by glmxndr**

### CODE REVIEW

**Comment by mr-c** [comment]
Is this really specific to mesos?

**Comment by glmxndr** [comment]
Can't say, but that's the only batch system I'm able to test against. I'm not sure which others call the singleMachine code.

**Comment by adamnovak** [comment]
I don't think this is Mesos-specific; the problem should affect all uses of the single machine batch system (both as the main batch system and for leader-only jobs in all the other batch systems that use it).

That being said, I don't really understand what the problem is (a deadlock between **threads** in the main Toil **process**? A dead **thread** in the main toil **process** causing the **process** to continue on with a bunch of non-daemon **threads** not doing anything? Or an unreaped ("zombie") child **process** that gets forked off somewhere and never `wait()`ed?) or how this PR is meant to fix it.

@glmxndr It looks like your stack trace in #2991 is *from* this PR (it is complaining about a join on line 144 of singleMachine.py, which isn't there until this patch is applied).

Is this supposed to result in all the previously-started workers being stopped as soon as a worker thread fails to start?

**Comment by glmxndr** [comment]
I'm not sure either as I don't know exactly what the threading model in Python is, and only know parts of toil's code. What I know is that we use toil like this: a Java service is notified of a job to run, launches a Process calling a bash script itself launching cwltoil. When launching a lot of processes in parallel, many Process instances never terminate. 

So I just launched a bash script going like this:
```
for iter in {0..100}
do
  cwltoil ... &
done
``` 

Some of them worked correctly. For some of though, I had in their logs the stacktrace I gave in the #2991 ticket. Doing a `ps ux | grep cwl` lists them as still up. "Zombie process" is probably not the correct term, but they are hanging when they should have been terminated.

You're absolutely right that the stacktrace I gave in the #2991 ticket is the wrong one, sorry about that, I'll fix this tomorrow.

The fix I propose here is probably not the right thing to do, but it prevented the cwltoil process to hang. I'll try to make a cleaner proposal tomorrow.

**Pull request closed without merging**
