### PR TITLE
SGE batch system change to support serial jobs.

### PR DESCRIPTION
**Pull request by douglowe**
Modified prepareQsub subroutine, so that it
will not specify a parallel environment when
only 1 CPU is needed. This will allow the
SGE scheduler to send the job straight to the
serial queue instead.

See: [https://github.com/DataBiosphere/toil/issues/4021](https://github.com/DataBiosphere/toil/issues/4021)

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * PR submitter writes their recommendation for a changelog entry here

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by mr-c** [comment]
This is great, @douglowe , thanks! Can you try writing a unit test that calls `prepareQsub` directly?

**Comment by mr-c** [comment]
Great! I've pushed this PR to https://github.com/DataBiosphere/toil/tree/issues/4021-sge-1core-jobs so this can go through the UCSC GitLab CI

**Comment by adamnovak** [comment]
We had [one of our tests fail](https://ucsc-ci.com/databiosphere/toil/-/jobs/8360) for apparently unrelated reasons:

```
__________________________ JobTest.testDAGConsistency __________________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/src/jobTest.py", line 145, in testDAGConsistency
    toil.start(i)
  File "/builds/databiosphere/toil/src/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1278, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/builds/databiosphere/toil/src/toil/leader.py", line 261, in run
    self.serviceManager.shutdown()
  File "/builds/databiosphere/toil/src/toil/serviceManager.py", line 219, in shutdown
    self.__service_starter.join()
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 241, in handler
    timeout_sigalrm(item, settings.timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 409, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >30.0s
```

I think that test might be flaky.

**Comment by mr-c** [comment]
Huh, another flaky test (I've retried it for now)

https://ucsc-ci.com/databiosphere/toil/-/jobs/8639#L5368

```
________________ SingleMachineBatchSystemTest.testProcessEscape ________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/batchSystems/batchSystemTest.py", line 665, in testProcessEscape
    fcntl.lockf(lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by mr-c** [comment]
@adamnovak CI passed on Friday; shall I force-merge?

**Comment by mr-c** [comment]
@adamnovak nevermind, I see a lot was merged since the last run (including the expanded type hints)

**Comment by mr-c** [comment]
Lint failed due to fixed boto3-stubs package; fix is at https://github.com/DataBiosphere/toil/pull/4025

**Review by DailyDreaming — APPROVED** [review]
LGTM.  Thank you @douglowe .

**Pull request merged**
