### PR TITLE
CWL Pipefish compatibility

### LINKED ISSUE #4633: If `--batchLogsDir` is set to a nonexistent directory, Slurm jobs all fail
Slurm won't run a job if you tell it to send the output to a file in a nonexistent directory. But Toil doesn't make sure the `--batchLogsDir` directory exists before running Slurm jobs, or even warn about it.

The workaround is to manually make the directory, but Toil ought to do it automatically, on the assumption that it is on a shared filesystem (or at least a place Toil can access on the leader node).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1423)
┆Issue Number: TOIL-1423

### PR DESCRIPTION
**Pull request by adamnovak**
This should fix #4633. It should allow running the workflow in https://github.com/DataBiosphere/toil/issues/4634#issuecomment-1769231393

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * CWL sub-workflows should now have their default input values applied
 * Directory objects shown to CWL containers should now always be full of files and never full of broken symlinks
 * Relative paths for `--workDir` and `--coordinationDir` should now be properly made absolute before being used by workers.

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
I don't actually have a data set small enough ti run through in a reasonable length of time without `--bypass-file-store`, and I haven't worked out the right way to `--bypass-file-store`, so I am going to propose this without actually manually testing the offending workflow to completion. With this, it sits around copying files for a long time, and I think it will eventually finish, but I got bored and stopped it.

**Review by DailyDreaming — APPROVED** [review]
This looks good to me!  Would be nice to have NFS testing in some capacity in the future, or we would have caught the need for 711 permissions on directories earlier I think.

**Review by mr-c — CHANGES_REQUESTED** [review]
This would be a good PR to re-run the CWL conformance tests on..

**Comment by adamnovak** [comment]
I'll see if I can get the CWL conformance tests to run on PRs where CWL-related files are touched, in addition to as part of the new integration test setup.

**Comment by adamnovak** [comment]
It looks like the CWL conformance tests do indeed fail after this change, but I haven't been able to get a log from CI for the failing tests, because on ARM we don't actually fetch the XML after the tests fail, and on the normal run we run conformance after a flaky BioContainers test which failed.

I think on ARM I got some logs that ID the failing tests:
```
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test 340 failed: toil-cwl-runner --clean=always --logDebug --statusWait=10 --retryCount=2 --caching=False --scale=0.1 --outdir=/var/tmp/tmpqle3g4_f --quiet tests/iwd/iwd-subdir-wf.cwl tests/iwd/iwd-subdir-job.yml
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test emitting a subdirectory from initial workdir
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Returned non-zero
```

```
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test 355 failed: toil-cwl-runner --clean=always --logDebug --statusWait=10 --retryCount=2 --caching=False --scale=0.1 --outdir=/var/tmp/tmpz9ljuh8u --quiet tests/colon:test.cwl tests/colon:test:job.yaml
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Confirm that colons are tolerated in input paths, string values, stdout shortcut, and output file & directory names
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Returned non-zero
```

```
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test 356 failed: toil-cwl-runner --clean=always --logDebug --statusWait=10 --retryCount=2 --caching=False --scale=0.1 --outdir=/var/tmp/tmpau_sp8pb --quiet tests/colon_test_output.cwl tests/colon_test_output_job.yaml
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Confirm that colons are tolerated in output directory names
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Compare failure expected: {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "result": {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "basename": "A:Gln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "class": "Directory",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "listing": [
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "basename": "hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "class": "File",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "size": 13
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         ]
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: got: {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "result": {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "basename": "A:Gln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "class": "Directory",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "listing": [
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "basename": "hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "class": "File",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "location": "file:///var/tmp/tmpau_sp8pb/A%3AGln2Cys_result/hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "nameext": ".txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "nameroot": "hello",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:                 "size": 13
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         ],
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "location": "file:///var/tmp/tmpau_sp8pb/A%3AGln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "nameext": "",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         "nameroot": "A:Gln2Cys_result"
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: caused by: failed comparison for key 'result': expected: {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "basename": "A:Gln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "class": "Directory",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "listing": [
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "basename": "hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "class": "File",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "size": 13
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     ]
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: got: {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "basename": "A:Gln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "class": "Directory",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "listing": [
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "basename": "hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "class": "File",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "location": "file:///var/tmp/tmpau_sp8pb/A%3AGln2Cys_result/hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "nameext": ".txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "nameroot": "hello",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:             "size": 13
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:         }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     ],
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "location": "file:///var/tmp/tmpau_sp8pb/A%3AGln2Cys_result",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "nameext": "",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "nameroot": "A:Gln2Cys_result"
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: }
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: caused by: {
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "basename": "hello.txt",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "class": "File",
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT:     "size": 13
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: } not found
```

```
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test 368 failed: toil-cwl-runner --clean=always --logDebug --statusWait=10 --retryCount=2 --caching=False --scale=0.1 --outdir=/var/tmp/tmp375x1s1w --quiet tests/cat-tool.cwl tests/octo.yml
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Test for correct handling of URL-quoting in filename to refer to filename containing a hash mark
INFO     toil.test.provisioners.clusterTest:clusterTest.py:113 STDOUT: Returned non-zero
```

Hopefully with that I can replicate and fix the problems.

**Comment by adamnovak** [comment]
I think the 4 failing tests are the CWL1.2.1 tests, and we just aren't pulling the right version of the tests to match the ones we actually expect to pass.

**Comment by adamnovak** [comment]
@mr-c can you and @stxue1 talk to each other and get the 1.2.1 tests back in and passing?

**Comment by mr-c** [comment]
@adamnovak sure; I sent @stxue1 an email

**Pull request merged**
