### PR TITLE
Lsf command parser

### PR DESCRIPTION
**Pull request by thiagogenez**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 When the word "Command" is trucked, it cannot be parsed. As a result, `logger.info` reports the entire (unnecessary for `INFO` level) content of `bjobs` to the file.

## Reviewer Checklist

 * [x] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [x] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [x] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [x] Read through the code changes. Make sure that it doesn't have:
    * [x] Addition of trailing whitespace.
    * [x] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [x] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [x] New functions or classes without informative docstrings.
    * [x] Changes to semantics not reflected in the relevant docstrings.
    * [x] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [x] New features without tests.
* [x] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [x] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks @thiagogenez 

Can you provide some real `bjobs` output that show this issue, and use that to write a unit test?

**Review by adamnovak — CHANGES_REQUESTED** [review]
I think we should be willing to take the PR without requiring a refactor to make the relevant code unit-testable, if we can put together a convincing argument that it is better this way. I've worked on too many PRs myself where the upstream project rejected them for not also fixing their own bad design decisions.

Unfortunately @thiagogenez I don't really understand what you mean by

> When the word "Command" is trucked, it cannot be parsed.

It looks like what the PR does is un-indent the bjobs output and remove whitespace at the starts of lines, and also replace commas with spaces when looking for the command. Is the problem that sometimes "Command" is split over multiple lines or something?

I agree with @mr-c that it would be very helpful if you could post an example of the particular `bjobs` output that this is supposed to handle that wasn't being handled properly before, or even describe why the new code is likely to be correct in a comment.

If we did want to add a unit test, this would have to be refactored substantially from the current design; we'd need the bjobs output parsing to be its own function so that we could call it on some example output without actually needing to invoke `bjobs`. Obviously if @thiagogenez wants to do that, that would be great. If not, perhaps it should become a ticket.

**Comment by thiagogenez** [comment]
Hi, @adamnovak, thank you for your message and apologises for the late reply @mr-c 

Please find below an example I was having here. 

> It looks like what the PR does is un-indent the bjobs output and remove whitespace at the starts of lines, and also replace commas with spaces when looking for the command. Is the problem that sometimes "Command" is split over multiple lines or something?

@adamnovak , In the example below you can see where the problem is

```
Job <2924748>, Job Name <toil_job_64>, User <thiagogenez>, Project <default>, S
                     tatus <RUN>, Queue <research-rh74>, Job Priority <50>, Com
                     mand <_toil_worker CactusBarRecursion file:/hps/nobackup/p
                     roduction/ensembl/thiagogenez/pairwises/arabidopsis/run/jo
                     bstore/3 kind-CactusBarRecursion/instance-iu6wo56x --conte
                     xt gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF
                     0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd
                     29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTow
                     kMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3Y
                     XlzlIeUgZSMBWFyZW5hlE51Yi4=>, Share group charged </thiago
                     genez>, Esub <esub>
```

Having this output from `bjobs`, we will have from the current code the following:

```
>>> memargs = ["bjobs", "-l", str(2924748)]
>>> bjobs = subprocess.check_output(memargs, universal_newlines=True)
>>> bjobs
'\nJob <2924748>, Job Name <toil_job_64>, User <thiagogenez>, Project <default>, S\n                     tatus <RUN>, Queue <research-rh74>, Job Priority <50>, Com\n                     mand <_toil_worker CactusBarRecursion file:/hps/nobackup/p\n                     roduction/ensembl/thiagogenez/pairwises/arabidopsis/run/jo\n                     bstore/3 kind-CactusBarRecursion/instance-iu6wo56x --conte\n                     xt gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF\n                     0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd\n                     29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTow\n                     kMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3Y\n                     XlzlIeUgZSMBWFyZW5hlE51Yi4=>, Share group charged </thiago\n                     genez>, Esub <esub>\nThu Mar 18 02:06:32: Submitted from host <noah-login-01>, CWD </hps/nobackup/pr\n                     oduction/ensembl/thiagogenez/pairwises/arabidopsis/run>, S\n                     pecified CWD </hps/nobackup/production/ensembl/thiagogenez\n                     /pairwises/arabidopsis/run/.>, Output File </tmp/toil_work\n                     flow_10e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf\n                     _2924748_std_output.log>, Error File </tmp/toil_workflow_1\n                     0e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf_29247\n                     48_std_error.log>, Requested Resources <select[(mem>4000)]\n                      rusage[mem=4000:duration=480, numcpus=1:duration=480]>;\nThu Mar 18 02:06:33: Started on <hx-noah-31-02>, Execution Home </homes/thiagog\n                     enez>, Execution CWD </hps/nobackup/production/ensembl/thi\n                     agogenez/pairwises/arabidopsis/run/.>;\nThu Mar 18 17:07:47: Resource usage collected.\n                     The CPU time used is 53936 seconds.\n                     MEM: 344 Mbytes;  SWAP: 1.3 Gbytes;  NTHREAD: 5\n                     PGID: 433168;  PIDs: 433168 433177 433179 444026 \n\n RUNLIMIT                \n 10085.0 min\n\n CORELIMIT MEMLIMIT\n      0 M     3.9 G \n\n MEMORY USAGE:\n MAX MEM: 2.5 Gbytes;  AVG MEM: 343 Mbytes\n\n SCHEDULING PARAMETERS:\n           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem\n loadSched   -     -     -     -    10.0     -    -     -   500M     -   1000M \n loadStop    -     -     -     -       -     -    -     -     -      -      -  \n\n          availcpus \n loadSched      1.0 \n loadStop        -  \n\n RESOURCE REQUIREMENT DETAILS:\n Combined: select[((mem>4000)) && (type == local)] order[r15s:pg] rusage[mem=40\n                     00.00:duration=8h:decay=0,numcpus=1.00:duration=8h:decay=0\n                     ] span[hosts=1]\n Effective: select[(((mem>4000))) && (type == local)] order[r15s:pg] rusage[mem\n                     =4000.00:duration=8h:decay=0,numcpus=1.00:duration=8h:deca\n                     y=0] span[hosts=1] \n\n'
>>> memregex = r"MAX MEM: (.*?);"
>>> memregex
'MAX MEM: (.*?);'
>>> meminfo = re.search(memregex, bjobs)
>>> meminfo
<re.Match object; span=(2123, 2143), match='MAX MEM: 2.5 Gbytes;'>
>>> s = " ".join(bjobs.split())
>>> s
'Job <2924748>, Job Name <toil_job_64>, User <thiagogenez>, Project <default>, S tatus <RUN>, Queue <research-rh74>, Job Priority <50>, Com mand <_toil_worker CactusBarRecursion file:/hps/nobackup/p roduction/ensembl/thiagogenez/pairwises/arabidopsis/run/jo bstore/3 kind-CactusBarRecursion/instance-iu6wo56x --conte xt gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF 0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd 29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTow kMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3Y XlzlIeUgZSMBWFyZW5hlE51Yi4=>, Share group charged </thiago genez>, Esub <esub> Thu Mar 18 02:06:32: Submitted from host <noah-login-01>, CWD </hps/nobackup/pr oduction/ensembl/thiagogenez/pairwises/arabidopsis/run>, S pecified CWD </hps/nobackup/production/ensembl/thiagogenez /pairwises/arabidopsis/run/.>, Output File </tmp/toil_work flow_10e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf _2924748_std_output.log>, Error File </tmp/toil_workflow_1 0e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf_29247 48_std_error.log>, Requested Resources <select[(mem>4000)] rusage[mem=4000:duration=480, numcpus=1:duration=480]>; Thu Mar 18 02:06:33: Started on <hx-noah-31-02>, Execution Home </homes/thiagog enez>, Execution CWD </hps/nobackup/production/ensembl/thi agogenez/pairwises/arabidopsis/run/.>; Thu Mar 18 17:07:47: Resource usage collected. The CPU time used is 53936 seconds. MEM: 344 Mbytes; SWAP: 1.3 Gbytes; NTHREAD: 5 PGID: 433168; PIDs: 433168 433177 433179 444026 RUNLIMIT 10085.0 min CORELIMIT MEMLIMIT 0 M 3.9 G MEMORY USAGE: MAX MEM: 2.5 Gbytes; AVG MEM: 343 Mbytes SCHEDULING PARAMETERS: r15s r1m r15m ut pg io ls it tmp swp mem loadSched - - - - 10.0 - - - 500M - 1000M loadStop - - - - - - - - - - - availcpus loadSched 1.0 loadStop - RESOURCE REQUIREMENT DETAILS: Combined: select[((mem>4000)) && (type == local)] order[r15s:pg] rusage[mem=40 00.00:duration=8h:decay=0,numcpus=1.00:duration=8h:decay=0 ] span[hosts=1] Effective: select[(((mem>4000))) && (type == local)] order[r15s:pg] rusage[mem =4000.00:duration=8h:decay=0,numcpus=1.00:duration=8h:deca y=0] span[hosts=1]'
>>> command = re.search(r"Command <(.*?)>", s)
>>> type(command)
<class 'NoneType'>
```

As the `command` is `None`, the `logger` will output `logger.info("Cannot Parse Max Memory Due to Missing Command String: %s", bjobs)`, printing the entire `bjobs` into the file.


On my patch, we will have:


```
>>> bjobs
'\nJob <2924748>, Job Name <toil_job_64>, User <thiagogenez>, Project <default>, S\n                     tatus <RUN>, Queue <research-rh74>, Job Priority <50>, Com\n                     mand <_toil_worker CactusBarRecursion file:/hps/nobackup/p\n                     roduction/ensembl/thiagogenez/pairwises/arabidopsis/run/jo\n                     bstore/3 kind-CactusBarRecursion/instance-iu6wo56x --conte\n                     xt gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF\n                     0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd\n                     29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTow\n                     kMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3Y\n                     XlzlIeUgZSMBWFyZW5hlE51Yi4=>, Share group charged </thiago\n                     genez>, Esub <esub>\nThu Mar 18 02:06:32: Submitted from host <noah-login-01>, CWD </hps/nobackup/pr\n                     oduction/ensembl/thiagogenez/pairwises/arabidopsis/run>, S\n                     pecified CWD </hps/nobackup/production/ensembl/thiagogenez\n                     /pairwises/arabidopsis/run/.>, Output File </tmp/toil_work\n                     flow_10e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf\n                     _2924748_std_output.log>, Error File </tmp/toil_workflow_1\n                     0e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf_29247\n                     48_std_error.log>, Requested Resources <select[(mem>4000)]\n                      rusage[mem=4000:duration=480, numcpus=1:duration=480]>;\nThu Mar 18 02:06:33: Started on <hx-noah-31-02>, Execution Home </homes/thiagog\n                     enez>, Execution CWD </hps/nobackup/production/ensembl/thi\n                     agogenez/pairwises/arabidopsis/run/.>;\nThu Mar 18 17:07:47: Resource usage collected.\n                     The CPU time used is 53936 seconds.\n                     MEM: 344 Mbytes;  SWAP: 1.3 Gbytes;  NTHREAD: 5\n                     PGID: 433168;  PIDs: 433168 433177 433179 444026 \n\n RUNLIMIT                \n 10085.0 min\n\n CORELIMIT MEMLIMIT\n      0 M     3.9 G \n\n MEMORY USAGE:\n MAX MEM: 2.5 Gbytes;  AVG MEM: 343 Mbytes\n\n SCHEDULING PARAMETERS:\n           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem\n loadSched   -     -     -     -    10.0     -    -     -   500M     -   1000M \n loadStop    -     -     -     -       -     -    -     -     -      -      -  \n\n          availcpus \n loadSched      1.0 \n loadStop        -  \n\n RESOURCE REQUIREMENT DETAILS:\n Combined: select[((mem>4000)) && (type == local)] order[r15s:pg] rusage[mem=40\n                     00.00:duration=8h:decay=0,numcpus=1.00:duration=8h:decay=0\n                     ] span[hosts=1]\n Effective: select[(((mem>4000))) && (type == local)] order[r15s:pg] rusage[mem\n                     =4000.00:duration=8h:decay=0,numcpus=1.00:duration=8h:deca\n                     y=0] span[hosts=1] \n\n'
>>> memregex = r"MAX MEM: (.*?);"
>>> memregex
'MAX MEM: (.*?);'
>>> meminfo = re.search(memregex, bjobs)
>>> meminfo
<re.Match object; span=(2123, 2143), match='MAX MEM: 2.5 Gbytes;'>
>>> s =' '.join(re.sub(r"\n\s*", "", bjobs).split(','))
>>> s
'Job <2924748>  Job Name <toil_job_64>  User <thiagogenez>  Project <default>  Status <RUN>  Queue <research-rh74>  Job Priority <50>  Command <_toil_worker CactusBarRecursion file:/hps/nobackup/production/ensembl/thiagogenez/pairwises/arabidopsis/run/jobstore/3 kind-CactusBarRecursion/instance-iu6wo56x --context gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTowkMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3YXlzlIeUgZSMBWFyZW5hlE51Yi4=>  Share group charged </thiagogenez>  Esub <esub>Thu Mar 18 02:06:32: Submitted from host <noah-login-01>  CWD </hps/nobackup/production/ensembl/thiagogenez/pairwises/arabidopsis/run>  Specified CWD </hps/nobackup/production/ensembl/thiagogenez/pairwises/arabidopsis/run/.>  Output File </tmp/toil_workflow_10e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf_2924748_std_output.log>  Error File </tmp/toil_workflow_10e83102-2e4b-4093-9128-2a52f4bbc65a_job_64_batch_lsf_2924748_std_error.log>  Requested Resources <select[(mem>4000)]rusage[mem=4000:duration=480  numcpus=1:duration=480]>;Thu Mar 18 02:06:33: Started on <hx-noah-31-02>  Execution Home </homes/thiagogenez>  Execution CWD </hps/nobackup/production/ensembl/thiagogenez/pairwises/arabidopsis/run/.>;Thu Mar 18 17:07:47: Resource usage collected.The CPU time used is 53936 seconds.MEM: 344 Mbytes;  SWAP: 1.3 Gbytes;  NTHREAD: 5PGID: 433168;  PIDs: 433168 433177 433179 444026 RUNLIMIT                10085.0 minCORELIMIT MEMLIMIT0 M     3.9 G MEMORY USAGE:MAX MEM: 2.5 Gbytes;  AVG MEM: 343 MbytesSCHEDULING PARAMETERS:r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    memloadSched   -     -     -     -    10.0     -    -     -   500M     -   1000M loadStop    -     -     -     -       -     -    -     -     -      -      -  availcpus loadSched      1.0 loadStop        -  RESOURCE REQUIREMENT DETAILS:Combined: select[((mem>4000)) && (type == local)] order[r15s:pg] rusage[mem=4000.00:duration=8h:decay=0 numcpus=1.00:duration=8h:decay=0] span[hosts=1]Effective: select[(((mem>4000))) && (type == local)] order[r15s:pg] rusage[mem=4000.00:duration=8h:decay=0 numcpus=1.00:duration=8h:decay=0] span[hosts=1] '
>>> command = re.search(r"Command <(.*?)>", s)
>>> command
<re.Match object; span=(134, 571), match='Command <_toil_worker CactusBarRecursion file:/hp>
>>> type(command)
<class 're.Match'>
>>> command.group(1)
'_toil_worker CactusBarRecursion file:/hps/nobackup/production/ensembl/thiagogenez/pairwises/arabidopsis/run/jobstore/3 kind-CactusBarRecursion/instance-iu6wo56x --context gASVtAAAAAAAAACMJXRvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF0Y2hTeXN0ZW2UjBRXb3JrZXJDbGVhbnVwQ29udGV4dJSTlCmBlH2UKIwRd29ya2VyQ2xlYW51cEluZm+UaACMEVdvcmtlckNsZWFudXBJbmZvlJOUTowkMTBlODMxMDItMmU0Yi00MDkzLTkxMjgtMmE1MmY0YmJjNjVhlIwGYWx3YXlzlIeUgZSMBWFyZW5hlE51Yi4='
>>>
```

The `command` variable will contain the string we are looking for. 

I hope this example my help guys. Sorry again for the late reply. I will try to add a unit test and push it into this branch.

**Review by adamnovak — CHANGES_REQUESTED** [review]
If the `\n` comes right before a space we expect, it will get lost, and the regex won't match. We'll also lose spaces in the command itself in such circumstances, but that's less of a problem I think.

Maybe we should  make all the spaces in the regexes optional, and also tolerate newlines when finding MAX MEM?

I'll try patching the PR...

**Review by adamnovak — APPROVED** [review]
I'm happy with this now because I fiddled with it.

**Review by DailyDreaming — APPROVED** [review]
@adamnovak @thiagogenez This looks good to me.  I've added a unit test.

**Pull request merged**
