### PR TITLE
Add lsf batch status call

### PR DESCRIPTION
**Pull request by nikhil**
Resolves: #3606 
Description in #3606 

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Whatsits now frobnicated

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by adamnovak — CHANGES_REQUESTED** [review]
Thanks for putting this together @nikhil! It definitely seems like a good idea.

Unfortunately, you've matched the style of the existing code, while we're trrying to institute new requirements where all new code has `snake_case` method names and variables, and also `arg: Type` type hints. Do you want to rename everything and add those, or do you want us to do that?

**Comment by nikhil** [comment]
No problem, @adamnovak. I will try to add the formatting fixes. If I miss something, feel free to add that as well.

**Comment by nikhil** [comment]
HI @adamnovak, I have added snake case variables and type hints for the functions. Please feel free to add/correct if I missed something.

**Comment by adamnovak** [comment]
I think we want the new methods (`parseBjobsRecord`, `coalesceJobExitCodes`, etc.) to be `snake_case` as well. I can just go ahead and change those.

**Comment by mr-c** [comment]
I fixed the snake case over in https://github.com/DataBiosphere/toil/pull/3680

**Pull request closed without merging**
