### PR TITLE
CWL:fix support for user space overrides

### PR DESCRIPTION
**Pull request by mr-c**
Actual fix for #2333

### CODE REVIEW

**Comment by DailyDreaming** [comment]
The failing cwl tests: http://jenkins.cgcloud.info/job/toil-pull-requests/4321/

**Comment by mr-c** [comment]
Thank you @DailyDreaming ; turns out that `cwltool` didn't have its own tests for the bioconda/biocontainers feature! That failure has been fixed via https://github.com/common-workflow-language/cwltool/pull/874

**Comment by mr-c** [comment]
@DailyDreaming Looks like the Jenkins-cgcloud-github account also needs its permission adjusted?

> Using context: jenkins-it
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
org.kohsuke.github.GHFileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}

http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/2612/console

**Comment by DailyDreaming** [comment]
@mr-c Will check on that!

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by DailyDreaming** [comment]
`No matching distribution found for cwltool==1.0.20180820141117`

http://jenkins.cgcloud.info/job/toil-pull-requests/4329/console

**Comment by mr-c** [comment]
Jenkins, test this please

**Pull request merged**
