### PR TITLE
don't list specific CWL features, try them all (and fix some CWL running bugs)

### PR DESCRIPTION
**Pull request by mr-c**
When running all the CWL v1.1 conformance tests, there are 9 more tests that successfully pass:

`246 tests passed, 7 failures, 0 unsupported features`

(4 "unsupported features" are now failing tests)

- [x] investigate regression of test 55 (fails in v1.0 as well)

### CODE REVIEW

**Comment by mr-c** [comment]
Good news, the new tests for `1.2-dev{1,2}` pass! Conditionals are still working. Reminder, they need both `cwlVersion: v1.2-dev2` in the CWL description and `--enable-dev` passed to `toil-cwl-runner`.

**Comment by mr-c** [comment]
Can we get this PR and #2959 as a 4.0.1 release?

**Comment by DailyDreaming** [comment]
@mr-c Definitely.  We're going to try to release on the first Wednesday of each month now, so May 6th.

**Comment by DailyDreaming** [comment]
@mr-c Everything should be updated.  Hopefully this passes!  I'd like to trim down redundant tests at some point to make these more efficient.

**Comment by mr-c** [comment]
Success, thank you @DailyDreaming !

**Pull request merged**
