### PR TITLE
bug is fixed in mypy_boto3

### LINKED ISSUE #4028: Any reason why "futures" is a requirement?
It's listed in [requirements-aws.txt](https://github.com/DataBiosphere/toil/blob/95982020dd263ed2b3ad5c41cd99fee19a6bdb30/requirements-aws.txt#L4)
```
futures>=3.1.1, <4
```
And seems to be behind this [Cactus CI error](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/8808) that I'm getting all of the sudden (via Cactus's [Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/4259ad72fce9c1e81c5c7f13b2dd3bb8619eb4dc/Dockerfile#L46-L48)):
```
ERROR: Could not find a version that satisfies the requirement futures<4,>=3.1.1; extra == "all" (from toil[all]) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
```
Where it seems that pip just stopped wanting to make wheels of it altogether.  I'm guessing this may have something to do with [futures](https://pypi.org/project/futures/) being python 2-specific?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1139)
┆friendlyId: TOIL-1139

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #4028 

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * small type change as boto3-stubs fixed a bug; drop unneeded `futures` dependency

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by adamnovak — CHANGES_REQUESTED** [review]
We also need to set the requirements file to require a new enough stubs module to have the type fix, or it will be possible for a Toil install to not want to upgrade the stubs but also not typecheck with `make mypy`.

**Comment by mr-c** [comment]
> We also need to set the requirements file to require a new enough stubs module to have the type fix, or it will be possible for a Toil install to not want to upgrade the stubs but also not typecheck with `make mypy`.

Good point, I added a dependency on the newer subs module in `requirements-dev.txt`

**Comment by mr-c** [comment]
@adamnovak ah, you beat me to it :-)

**Comment by adamnovak** [comment]
@mr-c Any idea what all the build steps on the lats PR are mad about, with not being able to find an acceptable `futures`?

**Comment by mr-c** [comment]
> @mr-c Any idea what all the build steps on the lats PR are mad about, with not being able to find an acceptable `futures`?

https://pypi.org/project/futures/ says

> It does not work on Python 3 due to Python 2 syntax being used in the codebase. Python 3 users should not attempt to install it, since the package is already included in the standard library.

I added a commit to drop the requirement :-)

**Review by adamnovak — APPROVED** [review]
This looks good!

**Pull request merged**
