### PR TITLE
Remove --disableCaching's argument

### LINKED ISSUE #3831: Option parse error with --disableCaching
When you pass `--disableCaching` as last option on the command line, you get a `RuntimeError` in `parseBool()`.
```
$ toil-cwl-runner --disableCaching cwltool cwljob
Traceback (most recent call last):
  File "/home/rapthor-mloose/code/toil/venv/bin/toil-cwl-runner", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')()
  File "/home/rapthor-mloose/code/toil/src/toil/cwl/cwltoil.py", line 3098, in main
    options = parser.parse_args([workdir] + args)
  File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.6/argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python3.6/argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "/home/rapthor-mloose/code/toil/src/toil/common.py", line 659, in parseBool
    raise RuntimeError("Could not interpret \"%s\" as a boolean value" % val)
RuntimeError: Could not interpret "cwltool" as a boolean value
```
This can be circumvented by adding `=yes` to the option, but that should not be necessary.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1048)
┆Issue Number: TOIL-1048

### PR DESCRIPTION
**Pull request by adamnovak**
This will fix #3831 by making the `--disableCaching` usage shown there the only acceptable one. As is, `--disableCaching` will try to eat the first positional argument if it comes last before the positional arguments, and will break command lines that look like they should work.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * **Breaking change!** `--disableCaching True/False` and `--disableCaching=True/False` command line argument forms are no longer accepted. Just pass or do not pass `--disableCaching` like the other `--disableX` flags.

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
New Gitlab didn't pick this up automatically so I started a pipeline at https://ucsc-ci.com/databiosphere/toil/-/pipelines/108.

**Comment by adamnovak** [comment]
Looks like https://ucsc-ci.com/databiosphere/toil/-/jobs/1959 had a Kubernetes CWL job randomly time out again, and managed to not emit any JUnit files with the logs. We *should* be using a cwlrunner that reports logs for timed-out tests, but we don't seem to have *any* JUnit output this time.

@mr-c Any idea how that can happen?

**Comment by mr-c** [comment]
> @mr-c Any idea how that can happen?

I don't know. I made a new cwltest release that includes your fixes for timed-out tests. https://github.com/common-workflow-language/cwltest/releases/tag/2.2.20211116163652 a.k.a. https://pypi.org/project/cwltest/2.2.20211116163652/

**Review by DailyDreaming — APPROVED** [review]
LGTM.  I've restarted the tests.

**Pull request merged**
