### PR TITLE
Update Sphinx and let its version float

### LINKED ISSUE #3010: Sphinx as a pinned dependency
Currenty sphinx is a dependency of toil. It is also pinned to version 1.7.5. Is sphinx really needed? If it is needed does it have to have its version pinned? This dependency make the installation trickier than necessary.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-527)
┆Issue Number: TOIL-527

### PR DESCRIPTION
**Pull request by adamnovak**
This should fix #3010. I had to hack the Sphinx TOC hack we got from DreamHost, which I think was the thing holding us back on Sphinx <1.7.6. I've made it a bit more robust against new Sphinx kwargs being added, and I've relaxed the Sphinx constraint to anything between the current latest version (2.4.4) and 3.0, whatever that will be.

@rikardn does that work for you? Or is there a particular Sphinx version other than the very latest that you want us to support?

### CODE REVIEW

**Comment by davidlougheed** [comment]
Is sphinx really needed in `setup.py`? This means that when toil is installed with pip sphinx gets dragged along with it, which seems unnecessary. Typically, this would be specified in some `requirements.txt` style file and only installed when needed for building docs.

**Comment by adamnovak** [comment]
We might be able to move it into the modules that `make prepare`
installs, alongside e.g. pytest.

I do think we only actually use Sphinx if someone runs `make docs`,
and not when people pull in Toil as a module.

**Comment by davidlougheed** [comment]
Yeah I did a quick search through the source and as far as I can tell it isn't used in toil proper (which makes sense...) - would save on some python site-packages pollution when toil is actually deployed

**Comment by rikardn** [comment]
Just to quantify the "pollution" that @davidlougheed  mentioned:

In my toil development venv:

```
$ pipdeptree -p toil
Warning!!! Possibly conflicting dependencies found:
* twine==3.1.1
 - requests [required: >=2.20, installed: 2.18.4]
* toil-container==1.1.6
 - toil [required: ==3.18.0, installed: 4.0.0a1]
* helpdev==0.6.10
 - psutil [required: >=5.6, installed: 3.0.1]
* flake8==3.7.9
 - pyflakes [required: >=2.1.0,<2.2.0, installed: 2.0.0]
 - pycodestyle [required: >=2.5.0,<2.6.0, installed: 2.4.0]
* launchpadlib==1.10.6
 - testresources [required: Any, installed: ?]
------------------------------------------------------------------------
toil==4.0.0a1
  - addict [required: <=2.2.0, installed: 2.2.0]
  - dill [required: ==0.2.7.1, installed: 0.2.7.1]
  - docker [required: ==2.5.1, installed: 2.5.1]
    - docker-pycreds [required: >=0.2.1, installed: 0.4.0]
      - six [required: >=1.4.0, installed: 1.12.0]
    - requests [required: >=2.5.2,!=2.18.0,!=2.12.2,!=2.11.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.8.24]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: >=1.21.1,<1.23, installed: 1.22]
    - six [required: >=1.4.0, installed: 1.12.0]
    - websocket-client [required: >=0.32.0, installed: 0.57.0]
      - six [required: Any, installed: 1.12.0]
  - future [required: Any, installed: 0.18.2]
  - pathlib2 [required: ==2.3.2, installed: 2.3.2]
    - six [required: Any, installed: 1.12.0]
  - psutil [required: >=3.0.1,<6, installed: 3.0.1]
  - python-dateutil [required: Any, installed: 2.7.3]
  - pytz [required: >=2012, installed: 2018.9]
  - requests [required: >=2,<3, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.8.24]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: >=1.21.1,<1.23, installed: 1.22]
  - six [required: >=1.10.0, installed: 1.12.0]
  - sphinx [required: >=2.4.4,<3, installed: 2.4.4]
    - alabaster [required: >=0.7,<0.8, installed: 0.7.8]
    - babel [required: >=1.3,!=2.0, installed: 2.6.0]
    - docutils [required: >=0.12, installed: 0.14]
    - imagesize [required: Any, installed: 1.0.0]
    - Jinja2 [required: >=2.3, installed: 2.10]
    - packaging [required: Any, installed: 19.2]
      - pyparsing [required: >=2.0.2, installed: 2.4.2]
      - six [required: Any, installed: 1.12.0]
    - Pygments [required: >=2.0, installed: 2.3.1]
    - requests [required: >=2.5.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.8.24]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: >=1.21.1,<1.23, installed: 1.22]
    - setuptools [required: Any, installed: 40.8.0]
    - snowballstemmer [required: >=1.1, installed: 1.9.1]
    - sphinxcontrib-applehelp [required: Any, installed: 1.0.1]
    - sphinxcontrib-devhelp [required: Any, installed: 1.0.1]
    - sphinxcontrib-htmlhelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
    - sphinxcontrib-qthelp [required: Any, installed: 1.0.2]
    - sphinxcontrib-serializinghtml [required: Any, installed: 1.1.3]
```

**Pull request merged**
