### PR TITLE
CWL symlinking files into work directory

### PR DESCRIPTION
**Pull request by mberacochea**
This is my attempt to symlink files into the work directory, following: https://github.com/DataBiosphere/toil/issues/2534#issuecomment-564278761

For our use case this is required, we have some reference DBs as inputs that are over 200 Gb. Copying those around is a huge overhead.

### CODE REVIEW

**Comment by mr-c** [comment]
I'm seeing a lot of
```
	  File "/builds/databiosphere/toil/src/toil/test/src/fileStoreTest.py", line 149, in _accessAndFail
	    raise RuntimeError("I do not like this file")
```
in the logs

**Comment by mberacochea** [comment]
> I'm seeing a lot of
> 
> ```
> 	  File "/builds/databiosphere/toil/src/toil/test/src/fileStoreTest.py", line 149, in _accessAndFail
> 	    raise RuntimeError("I do not like this file")
> ```
> 
> in the logs

I see, the tests that are failing don't run with "TOIL_TEST_QUICK=True make test_offline".

I'll fix that.

**Comment by DailyDreaming** [comment]
Tests will appear here: https://ucsc-ci.com/databiosphere/toil/-/commit/0fda00d370970ad19beef912dcb29b71a351ad8f/pipelines?ref=issues%2F2534-make-cwl-use-symlinks

**Review by DailyDreaming — APPROVED** [review]
LGTM.  Thank you @mberacochea .

**Comment by mberacochea** [comment]
Brilliant, thank you!

**Pull request merged**
