### PR TITLE
Add type hints to toilStats.py

### PR DESCRIPTION
**Pull request by jonathanxu18**
Added type hints to src/toil/utils/toilStats.py so it can be checked under mypy during linting.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

## Reviewer Checklist

 * [x] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [x] Read through the code changes. Make sure that it doesn't have:
    * [x] Addition of trailing whitespace.
    * [x] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [x] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [x] New functions or classes without informative docstrings.
    * [x] Changes to semantics not reflected in the relevant docstrings.
    * [x] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [x] New features without tests.
* [x] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [x] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by adamnovak — APPROVED** [review]
This looks good to me.

**Review by DailyDreaming — CHANGES_REQUESTED** [review]
Merge might've gone wrong.

```
Traceback (most recent call last):
  File "/home/travis/build/DataBiosphere/toil/src/toil/test/utils/utilsTest.py", line 44, in <module>
    from toil.utils.toilStats import getStats, processData
  File "/home/travis/build/DataBiosphere/toil/src/toil/utils/toilStats.py", line 23, in <module>
    from toil.jobstores.abstractJobStore import AbstractJobStore
ModuleNotFoundError: No module named 'toil.jobstores'
```

**Review by DailyDreaming — APPROVED** [review]
LGTM.

**Review by DailyDreaming — CHANGES_REQUESTED** [review]
Lint test shows something new:

```
$ make mypy
/builds/databiosphere/toil/contrib/admin/mypy-with-ignore.py
src/toil/utils/toilStats.py:70: error: Missing return statement
src/toil/utils/toilStats.py:270: error: Missing return statement
src/toil/utils/toilStats.py:285: error: Returning Any from function declared to return "SupportsLessThan"
src/toil/utils/toilStats.py:290: error: Returning Any from function declared to return "SupportsLessThan"
src/toil/utils/toilStats.py:293: error: Returning Any from function declared to return "SupportsLessThan"
```

Once that's addressed, I think that this is good to merge.

**Review by mr-c — APPROVED** [review]

**Pull request merged**
