### PR TITLE
Stop deleting chained-to jobs which fail as orphaned jobs

### LINKED ISSUE #4504: Unable to restart failed job due to NoSuchFileException
I have a job that's running out of memory on slurm and getting killed.  When I go to restart it with `singleMachine` (which normally works fine), I get an error like this

```
[2023-06-19T06:47:30-0700] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'vg_to_og' kind-clip_vg/instance-fh8zs_29 v36
Exit reason: None
[2023-06-19T06:47:30-0700] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'vg_to_og' kind-clip_vg/instance-fh8zs_29 v38
[2023-06-19T06:47:30-0700] [MainThread] [W] [toil.leader] Log from job "kind-clip_vg/instance-fh8zs_29" follows:
=========>
        [2023-06-19T06:47:29-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-06-19T06:47:29-0700] [MainThread] [I] [toil] Running Toil version 5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9 on host mustard.prism.
        [2023-06-19T06:47:29-0700] [MainThread] [I] [toil.worker] Working on job 'vg_to_og' kind-clip_vg/instance-fh8zs_29 v37
        Traceback (most recent call last):
          File "/private/home/hickey/dev/cactus.pangenome/venv-cactus-pangenome/lib/python3.10/site-packages/toil/worker.py", line 377, in workerScript
            job = Job.loadJob(jobStore, jobDesc)
          File "/private/home/hickey/dev/cactus.pangenome/venv-cactus-pangenome/lib/python3.10/site-packages/toil/job.py", line 2657, in loadJob  
            with manager as fileHandle:
          File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
            return next(self.gen)
          File "/private/home/hickey/dev/cactus.pangenome/venv-cactus-pangenome/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 657, in read_file_stream
            self._check_job_store_file_id(file_id)
          File "/private/home/hickey/dev/cactus.pangenome/venv-cactus-pangenome/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 839, in _check_job_store_file_id
            raise NoSuchFileException(jobStoreFileID)
        toil.jobStores.abstractJobStore.NoSuchFileException: File 'files/for-job/kind-vg_to_og/instance-yybmsm3i/cleanup/file-c87a04ee86fc4e938468eed073ab3462/stream' does not exist.
        [2023-06-19T06:47:30-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mustard.prism
```
This happens every time: I run the workflow from the beginning; it dies, it won't restart.  I rerun from the beginning with a bit more memory, it dies again, won't restart etc. 

This is new code on my end, where `vg_to_og` is a FollowOn to `clip_vg`
```
hprc-jun16-slurm-mc.log:	[2023-06-17T09:54:18-0700] [MainThread] [I] [toil.worker] Chaining from 'clip_vg' kind-clip_vg/instance-fh8zs_29 v3 to 'vg_to_og' kind-vg_to_og/instance-yybmsm3i v1
```
but there doesn't seem anything really different about it.  I've only ever seen this issue come up now using the latest Toil release.  

@adamnovak writes
>I don't think this is supposed to happen; we're supposed to only commit the job descriptions after the bodies are on disk, and we're supposed to leave the bodies around until the jobs that made them are cleaned up, which won't happen until after all their children/follow-ons finish.

>It also looks like chaining is involved here, since the job's name isn't the same as the name that was used to make the ID it is under. Maybe there's a consistency error in the chaining logic?

> There might be some kind of consistency bug then, related to cleanup-able files for a chained-to job not being cleaned up at the right time relative to deletion of the chained-from job description. I don't think we did anything in 5.11 that ought to introduce that, but it's possible.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1352)
┆Issue Number: TOIL-1352

### PR DESCRIPTION
**Pull request by adamnovak**
This will fix #4504 by improving the semantics of `jobsToDelete` (which is now `merged_jobs`, to make it clear that it has very different semantics than `filesToDelete`, which journals file deletions).

Previously, when a job was chained to, we would put it in `jobsToDelete` on the chaining-from job, and then delete it when that job finished successfully.

But we also at some point started cutting the successor relationship to the chained-to job, which meant that if the chained-to job failed, when we went through the job tree during the restart, we would find the chained-to job's original job description under its original ID as an orphaned job and delete it.

This adds code to treat the original chained-to job as more properly merged into the chained-from job, and so still reachable from the root.

I'm also making the `filesToDelete` system more sure about what it is actually supposed to be used for.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Chained-to jobs which fail should no longer be deleted as orphans upon workflow restart (#4504)

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
@glennhickey Do you want to see if this stops you from reproducing #4504? Or if a job getting chained to, and failing, and then being deleted as an orphan, is consistent with your full logs?

**Review by DailyDreaming — APPROVED** [review]
LGTM.

**Comment by adamnovak** [comment]
Looks like I actually added a bug here. In `CachingFileStoreTestWithAwsJobStore.testAsyncWriteWithCaching` CI managed to trigger:

```
	  File "/builds/databiosphere/toil/src/toil/job.py", line 1048, in replace
	    raise RuntimeError("Trying to take on the ID of a job that is in the process of being committed!")
```

**Comment by glennhickey** [comment]
@adamnovak I can confirm that this change does indeed fix my issue.

**Comment by adamnovak** [comment]
It looks like our job description deepcopy never worked quite right.

To fix the fighting over who is allowed to write to what copy of the job description that made the test fail, I'm moving responsibility for snapshotting job descriptions for asynchronous commit into the file store that does the asynchronous committing and out of the worker. But that means now I'm doing chained deepcopies and that's what didn't work. But I *think* I have it all working now.

**Pull request merged**
