### PR TITLE
CWL Test #213: Evaluate loadContents if True for StepValueFrom objects.

### LINKED ISSUE #3257: CWL conformance test 213 fails
┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-681)
┆Issue Number: TOIL-681
┆Epic: Refine Toil to support CWL development

### PR DESCRIPTION
**Pull request by DailyDreaming**
This PR adds support for CWL1.1 and allows us to pass conformance test 213.

Input files evaluated in `StepValueFrom` weren't resolving the toil specific uris we use, so were returning `None` for toil paths, which were seen as files that don't exist.

Adds the check if `loadContents == True`, as well as the `loadContents` content size limit.

In cwltool, this is done here: https://github.com/common-workflow-language/cwltool/blob/876e5bd384843bae41c98dcd36641bc71b2bf729/cwltool/workflow_job.py#L647

Closes #3257 .

### CODE REVIEW

**Review by mr-c — APPROVED** [review]
Huzzah! Did any additional tests pass?

**Comment by DailyDreaming** [comment]
@mr-c I only tried 213 and 236.  I'll try some of the CWL1.2 tests though too!

**Comment by altairwei** [comment]
I've got the same problem:

```log
	[2020-10-10T16:19:27+0800] [MainThread] [E] [toil.cwl.cwltoil] Got exception 'Not a file URI: /public/home/graham/src/rhapsody-wta/data/annotations/Homo_sapiens.GRCh38.99.gtf' while copying '/public/home/graham/src/rhapsody-wta/data/annotations/Homo_sapiens.GRCh38.99.gtf'
	Traceback (most recent call last):
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 999, in run
	    index, existing))
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/cwltool/utils.py", line 353, in adjustFileObjs
	    visit_class(rec, ("File",), op)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/cwltool/utils.py", line 295, in visit_class
	    visit_class(rec[d], cls, op)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/cwltool/utils.py", line 298, in visit_class
	    visit_class(d, cls, op)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/cwltool/utils.py", line 293, in visit_class
	    op(rec)
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 703, in uploadFile
	    uploadfunc, fileindex, existing, file_metadata["location"])
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 637, in write_file
	    index[file_uri] = "toilfs:" + writeFunc(rp).pack()
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 711, in writeGlobalFileWrapper
	    schema_salad.ref_resolver.uri_file_path(fileuri))
	  File "/public/home/graham/miniconda3/envs/wta/lib/python3.6/site-packages/schema_salad/ref_resolver.py", line 78, in uri_file_path
	    raise ValidationException("Not a file URI: {}".format(url))
	schema_salad.exceptions.ValidationException: Not a file URI: /public/home/graham/src/rhapsody-wta/data/annotations/Homo_sapiens.GRCh38.99.gtf
	[2020-10-10T16:19:28+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host comput22
```

**Comment by altairwei** [comment]
How do I get around this issue in version 4.2.0 other than installing toil from source?

**Comment by DailyDreaming** [comment]
@altairwei I suppose you could either do a cherry pick of this commit into your toil root dir, or edit `src/toil/cwl/cwltoil.py` directly with the changes from here, which wouldn't be too bad.

**Comment by altairwei** [comment]
> @altairwei I suppose you could either do a cherry pick of this commit into your toil root dir, or edit `src/toil/cwl/cwltoil.py` directly with the changes from here, which wouldn't be too bad.

@DailyDreaming Thanks! I've installed toil from the source of the master branch, version number about 4.3.0a1.

**Pull request merged**
