### PR TITLE
batchSystem generates a key error instead of a usage message 

### PR DESCRIPTION
**Pull request by jeffrey856**
Added choices argparse to list of uniqueNames().

### CODE REVIEW

**Review by adamnovak — CHANGES_REQUESTED** [review]
I think this will stop accepting the extra names we defined in _DEFAULT_REGISTRY here:

https://github.com/DataBiosphere/toil/blob/8491a03a620f09f3e477405b5d4a5fabfe92c8bd/src/toil/batchSystems/registry.py#L52-L102

What does the help look like if we add another function to that file (`allAvailableNames()`?) to expose that list, and use that as the choices? Does argparse print out all the choices for us even if we don't want to display everything we accept?

Or should we take the opportunity to get rid of all those extra names and force people to always spell and capitalize each batch system exactly one way (and delete all the duplicates)?

**Comment by jeffrey856** [comment]
@adamnovak If we were to do `choice = allAvailableNames()`, it would output all the choices even if we wouldn't want to. This is the sample that I have ran below. Ideally, I don't think we want to force our users to use all caps to use a certain batchSystem however that is the most straight-forwarded solution. 

Screen Shot 2020-09-14 at 15 19 02

**Comment by adamnovak** [comment]
@DailyDreaming Do you think it would be a problem if we dropped down to accepting only one form of each batch system name? Maintaining the ability to use several makes it hard to use Argparse to make our UI nice.

**Comment by DailyDreaming** [comment]
@adamnovak I don't mind, since accepting multiple cases with capitalization isn't normal, so long as everything is moved to lower-case only.  We'll have to find all cases in the docs, and also bump the major version to 5.0.0 since these will be considered breaking changes.

If we do, I think that we should also consider moving all of the options to `snake_case`.  I think some people get (understandably) hung up on things like `--nodestorage` vs. `--nodeStorage`.

**Review by adamnovak — APPROVED** [review]

**Comment by adamnovak** [comment]
I'm going to go ahead and merge this. We can bump the version to 5 as part of the next release process, right?

**Comment by adamnovak** [comment]
This fixed #3038.

**Pull request merged**
