### PR TITLE
Replace mentions of CoreOS with flatcar

### LINKED ISSUE #3435: Remove mentions of coreOS and replace with flatcar.
┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-787)
┆Issue Number: TOIL-787

### PR DESCRIPTION
**Pull request by jonathanxu18**
Closes #3435.

Removed mentions of CoreOS in the docs and in comments.

Migrated to Container Linux Config for provisioning since cloud-config is deprecated.

### CODE REVIEW

**Review by DailyDreaming — APPROVED** [review]
This looks good to me.  Thanks for moving to the Container Linux Config!

**Review by DailyDreaming — COMMENTED** [review]
@jonathanxu18 Can you investigate why this is failing?

```
make test tests=src/toil/test/utils/utilsTest.py::UtilsTest::testAWSProvisionerUtils
```

```
=================================== FAILURES ===================================
______________________ UtilsTest.testAWSProvisionerUtils _______________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/utils/utilsTest.py", line 152, in testAWSProvisionerUtils
    '--provisioner=aws', '--zone=us-west-2a', '--logLevel=DEBUG'])
  File "/builds/databiosphere/toil/src/toil/lib/bioio.py", line 34, in system
    subprocess.check_call(command, shell=isinstance(command, str), bufsize=-1)
  File "/usr/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 341, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 200, in handler
    timeout_sigalrm(item, params.timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 375, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >1200.0s
```

**Review by DailyDreaming — CHANGES_REQUESTED** [review]
@jonathanxu18 Can you investigate why this is failing?

```
make test tests=src/toil/test/utils/utilsTest.py::UtilsTest::testAWSProvisionerUtils
```

```
=================================== FAILURES ===================================
______________________ UtilsTest.testAWSProvisionerUtils _______________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/utils/utilsTest.py", line 152, in testAWSProvisionerUtils
    '--provisioner=aws', '--zone=us-west-2a', '--logLevel=DEBUG'])
  File "/builds/databiosphere/toil/src/toil/lib/bioio.py", line 34, in system
    subprocess.check_call(command, shell=isinstance(command, str), bufsize=-1)
  File "/usr/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 341, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 200, in handler
    timeout_sigalrm(item, params.timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/pytest_timeout.py", line 375, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.7/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >1200.0s
```

**Review by adamnovak — APPROVED** [review]
This looks good to me. It shouldn't affect functionality, improves the docs, and passes tests now.

**Review by adamnovak — CHANGES_REQUESTED** [review]
Wait hold on you forcot `common.mk`:

https://github.com/DataBiosphere/toil/blob/63613ede49e84d9d922c6d78983bcec868ef4e60/common.mk#L29

**Review by DailyDreaming — APPROVED** [review]
LGTM.

**Pull request merged**
