### PR TITLE
Update Cactus and exclude broken networkx

### LINKED ISSUE #4106: Toil Cactus integration test failing due to NetworkX bug
https://ucsc-ci.com/databiosphere/toil/-/jobs/15482#L2236

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.9/dist-packages/toil/worker.py", line 381, in workerScript
	    job = Job.loadJob(jobStore, jobDesc)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 2292, in loadJob
	    job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 1918, in _unpickle
	    runnable = unpickler.load()
	  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/reportviews.py", line 1290, in __setstate__
	    self._adjdict = G._pred if hasattr(G, "pred") else G._adj
	AttributeError: 'DiGraph' object has no attribute '_adj'

I think maybe the Cactus we use is hitting https://github.com/networkx/networkx/issues/5655 which was maybe introduced in a new NetworkX release.

We will probably have to ignore the Cactus integration test until Cactus or NetworkX fixes this, and then update to a fixed Cactus.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1172)
┆friendlyId: TOIL-1172

### PR DESCRIPTION
**Pull request by adamnovak**
This should fix #4106 by pinning what probably was a working networkx version.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Toil now excludes the broken NetworkX 2.8.1 release, which breaks pickling and the Cactus integration tests

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
This doesn't work, I think because we seem to be juggling several networkx versions: 2.4 from Ubuntu, 2.6.3 that gets installed in the Toil container build virtualenv because the CWL extras want a networkx, and the 2.8.0 that I am trying to pin here.

**Comment by adamnovak** [comment]
I built the Docker for this myself and tested Cactus on Kubernetes, so I think it is going to actually work now when it gets around to running.

<details>
<summary>My Kubernetes job</summary>

```
kubectl apply --namespace toil -f - <<'EOF'
apiVersion: batch/v1
kind: Job
metadata:
  name: adamnovak-leader
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 10000
  template:
    spec:
      containers:
      - name: anovak-container
        image: quay.io/adamnovak/toil:py3.9 
        imagePullPolicy: Always
        env:
          - name: TOIL_APPLIANCE_SELF
            value: quay.io/adamnovak/toil:py3.9
          - name: TOIL_KUBERNETES_OWNER
            value: adamnovak
          - name: TOIL_AWS_SECRET_NAME
            value: shared-s3-credentials
          - name: TOIL_WORKDIR
            value: /var/lib/toil
          - name: SINGULARITY_CACHEDIR
            value: /var/lib/toil/singularity-cache
          - name: TOIL_KUBERNETES_HOST_PATH
            value: /data/scratch
          - name: TOIL_OWNER_TAG
            value: anovak@soe.ucsc.edu
          - name: SINGULARITY_DOCKER_HUB_MIRROR
            value: http://docker-registry.toil
        command:
          - /bin/bash
          - -c
          - |
            MAIN_PYTHON_PKG=python3.9
            mkdir -p /var/lib/toil/singularity-cache
            set -e
            ${MAIN_PYTHON_PKG} -m virtualenv --system-site-packages venv
            . venv/bin/activate
            pip install -U pip wheel
            mkdir -p ${TOIL_WORKDIR}
            mkdir -p ${SINGULARITY_CACHEDIR}
            BUCKET_NAME=toil-test-$RANDOM-$RANDOM-$RANDOM
            cd
            git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
            cd cactus
            git fetch origin
            git checkout 3345cc0ce8dbf27ec765178f6031c5558d6d3525
            git submodule update --init --recursive
            pip install --upgrade setuptools pip
            pip install --upgrade .
            time cactus --batchSystem kubernetes --consCores 2 --binariesMode singularity --setEnv SINGULARITY_DOCKER_HUB_MIRROR --clean always aws:us-west-2:adamnovak-cactus-test examples/evolverMammals.txt examples/evolverMammals.hal --root mr --defaultDisk "8G" --logDebug
        resources:
          requests:
            cpu: 4000m
            memory: "4Gi"
            ephemeral-storage: "10Gi"
          limits:
            cpu: 4000m
            memory: "4Gi"
            ephemeral-storage: "10Gi"
        volumeMounts:
          - mountPath: /scratch
            name: scratch
          - mountPath: /root/.aws
            name: s3-credentials
          - mountPath: /var/lib/toil
            name: toil-hostpath
          - mountPath: /var/run/user
            name: toil-coord
      restartPolicy: Never
      volumes:
      - name: scratch
        emptyDir: {}
      - name: s3-credentials
        secret:
          secretName: shared-s3-credentials
      - name: toil-hostpath
        hostPath:
          path: /data/scratch
          type: Directory
      - name: toil-coord
        hostPath:
          path: /var/run/user
          type: Directory
      serviceAccountName: toil-svc
EOF
```

</details>

**Comment by adamnovak** [comment]
As far as I can tell the integration tests didn't actually need psutil or numpy, so I dropped them.

**Review by DailyDreaming — APPROVED** [review]
LGTM.  I'm just going to merge this.

**Comment by adamnovak** [comment]
Looks like maybe we needed `psutil` after all:

```
$ toil clean aws:us-west-2:${BUCKET_NAME}
Traceback (most recent call last):
  File "/builds/databiosphere/toil/venv/bin/toil", line 8, in <module>
    sys.exit(main())
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/utils/toilMain.py", line 15, in main
    modules = loadModules()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/utils/toilMain.py", line 50, in loadModules
    from toil.utils import toilClean  # noqa
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/utils/toilClean.py", line 17, in <module>
    from toil.common import Toil, parser_with_common_options
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/common.py", line 57, in <module>
    from toil.batchSystems.options import (add_all_batchsystem_options,
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/batchSystems/options.py", line 24, in <module>
    from toil.lib.threading import cpu_count
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/toil/lib/threading.py", line 30, in <module>
    import psutil  # type: ignore
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 95, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
```
https://ucsc-ci.com/databiosphere/toil/-/jobs/15898

**Pull request merged**
