### PR TITLE
Fix output file name conflicts

### PR DESCRIPTION
**Pull request by ndonyapour**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * PR submitter writes their recommendation for a changelog entry here

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by ndonyapour** [comment]
Hello, 
This PR attempts to resolve the issue of overwriting output files with the same name by copying them to separate directories.

**Comment by mr-c** [comment]
Thank you @ndonyapour for your contribution. Can you provide an example of the problem or link to an issue with more details?

**Comment by ndonyapour** [comment]
This is the [workflow](https://github.com/PolusAI/workflow-inference-compiler/blob/master/examples/scattering_scaling.yml) written in WIC format that converts to a CWL code and the output is  incorrect when `separateDirs=False`
 
```
(toil_demo) [donyapourn2@node01 workflow-inference-compiler]$ find . -name "stdout*" 
./outdir_toil/stdout
./outdir_toil/stdout_2
(toil_demo) [donyapourn2@node01 workflow-inference-compiler]$ find . -name "stdout*"  | xargs cat
1
10
```
While using the `separateDirs=True` option, the output appears in separate directories and is correct.
```
(toil_demo) [donyapourn2@node01 workflow-inference-compiler]$ rm -rf outdir
(toil_demo) [donyapourn2@node01 workflow-inference-compiler]$ find . -name "stdout*"  
./outdir_toil/stga49aad19-5757-4a53-9b88-ee1ab18a5596/stdout
./outdir_toil/stg79d3496e-c0f4-4125-918c-e8cafe4c0ca0/stdout
./outdir_toil/stgec2cc173-78a7-44aa-b953-8b286d002731/stdout
./outdir_toil/stg0c5e2549-a052-41f4-abe4-57ce33576108/stdout
./outdir_toil/stg0392ff83-4bc7-44de-b17f-2c1207f19c25/stdout
./outdir_toil/stg3b2edfc5-8b0a-4baf-9140-c9e9cb43871b/stdout
./outdir_toil/stgb6b4e331-b23b-4d7e-803e-4ed241aef1c4/stdout
./outdir_toil/stgd8cb8e17-e876-4631-b00c-349e846e91b1/stdout
./outdir_toil/stg72828930-c806-42fb-853d-d8fec8c79e69/stdout
./outdir_toil/stg0cd77563-26e1-459c-b8d5-15bb08535c6c/stdout
(toil_demo) [donyapourn2@node01 workflow-inference-compiler]$ find . -name "stdout*"  | xargs cat
1
2
3
4
5
6
7
8
9
10
```

**Comment by mr-c** [comment]
Thank you @ndonyapour ; can you share the CWL version of https://github.com/PolusAI/workflow-inference-compiler/blob/master/examples/scattering_scaling.yml ?

**Comment by ndonyapour** [comment]
Below is the CWL version code files and the command we used to run it.
```
toil-cwl-runner --outdir outdir_toil --jobStore file:./jobStore_scattering_scaling --batchSystem slurm --dont_allocate_mem --statePollingWait 0 --retryCount 0 --maxCores 128 --maxLocalJobs 128 --disableAutoDeployment True --stats --clusterStats clusterStats.json --singularity --workDir workdir --coordinationDir coorddir --caching false --disableProgress autogenerated/scattering_scaling.cwl autogenerated/scattering_scaling_inputs.yml
```
[cwl_version.zip](https://github.com/DataBiosphere/toil/files/15028040/cwl_version.zip)

**Comment by adamnovak** [comment]
Having looked at this again. it looks like actually we must have a bug where the logic that makes `stdout_2` was supposed to continue on and make `_3`, `_4`, etc., but didn't.

This change works around that bug at the cost of always putting files in UUID directories, even when not actually necessary to prevent conflicts.

**Comment by adamnovak** [comment]
The existing file name conflict code is here:
https://github.com/DataBiosphere/toil/blob/435d9c14add745000db7f18f0f7259194324e7ef/src/toil/cwl/cwltoil.py#L946-L956

I think the problem might be that `targets` is not preserved between visits to multiple conflicting files, and/or that the condition on the `while` loop checks for additional conflicts with the new name in `targets` and not in `self._pathmap` (which might require an inner scan since `_pathmap` is not keyed by destination path). So we can only resolve one conflict and not a chain of them, so everything but the first file gets a `_2`.

**Comment by adamnovak** [comment]
It looks like the provided CWL workflow is missing the CWL files for the steps (`echo.cwl`, etc.).

**Comment by adamnovak** [comment]
Thanks for finding the problem @ndonyapour, but I'm going to close this in favor of #4888 which solves it in a different way, by making the `_` renaming we are supposed to have been using actually work properly for more than 2 files.

**Pull request closed without merging**
