### PR TITLE
use displayName for CWLJob to show stats in toil --stats

### PR DESCRIPTION
**Pull request by ionox0**
The purpose of this is to show the cwl file names (or presumably the step's `id`), in the `toil stats` command for each job.
screen shot 2018-10-05 at 4 13 21 pm

### CODE REVIEW

**Comment by ionox0** [comment]
Please let me know if there is another branch I should submit this to. 

Also any advice on testing / contributing requirements would be helpful!

**Comment by DailyDreaming** [comment]
This looks great!  Submitting directly to `master` is the convention we use.

I'd recommend a `git pull` to resolve conflicts, but I expect these to pass.  Additional unittests are always welcome if you'd like to add something for this.  Though this does not affect core functionality so I'm alright with merging without.  Thanks for the PR!

**Comment by DailyDreaming** [comment]
Jenkins, add to the whitelist please.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Jenkins, add to the whitelist please.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Pull request merged**
