### PR TITLE
Continue the pymesos port

### PR DESCRIPTION
**Pull request by adamnovak**
I'm PR-ing this against the other PR to see if I can convince the tests to run, because Courtyard can't run the tests properly due to the absence of Docker availability.

### CODE REVIEW

**Comment by adamnovak** [comment]
This is my attempt to finish #2338.

It seems like it might be done (once debugged), although it really shouldn't be this simple.

**Comment by adamnovak** [comment]
I think the problem I am having with the non-integration tests is that we have a very old Mesos (0.25.1, as installed in #872) on our Jenkins nodes, and those tests just go ahead and fire up whatever version of Mesos is locally installed. Something about using that old Mesos with pymesos seems to be causing the executor to be killed, ostensibly for running out of memory, as soon as the executor checks in with the agent, and before any actual jobs can start.

I think rather than troubleshooting compatibility indefinitely, we ought to upgrade Jenkins' Mesos. The tests that fail seem to work on Mesos 1.4, and all the Docker stuff on 1.0.1 works fine, so maybe we just need something 1.0+. Unfortunately, I'm not sure *how* to upgrade Jenkins' Mesos. I think we need to replace the AMI used for "toil-jenkins-slave" nodes, ami-3f6dfb47, with a new AMI that includes the changes, but I'm not sure how that AMI was generated.

@DailyDreaming Do you know how we came up with the AMIs currently in use?

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
Failures due to upgrading the AMI with `sudo apt update && sudo apt upgrade` which raised `mesos` to version 1.7.0 on the jenkins-slave:
http://jenkins.cgcloud.info/job/toil-pull-requests/4445/
http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/2738/

Have since modified the jenkins-slave AMI to only upgrade `mesos`, and only to version `1.0.1` in order to match the leader node and will test that next.

**Comment by DailyDreaming** [comment]
Jenkins, test this please.

**Comment by DailyDreaming** [comment]
@adamnovak To answer your earlier questions pretty belatedly... the `jenkins-slave` AMI seems to be an Ubuntu 14.04 image with likely an old version of the commands in: https://github.com/DataBiosphere/toil/blob/master/docker/Dockerfile.py , which I assume was once `mesos version 0.25.1`.

AMIs are generally generated from other AMIs.  So to make a new one with an update, create an instance with the AMI in the AWS browser, ssh into that instance, make changes, exit, then in the instances list you can select "make an AMI from this image".  This generates s new AMI that's a clone of the old one with your changes.  Jenkins has a field in the general settings for which AMIs get spun up for which repos.  I've made an AMI for `toil` for the `jenkins-slave` with the upgraded `mesos 1.0.1`.  I haven't changed anything for `vg`, but can if you want me to.

I'll try upgrading the system further (`Ubuntu 16.04` at the very least, though hopefully `Ubuntu 18.04`, then on to the highest `mesos` version that works), but for now, hopefully this'll work for PRs with code not touching `mesos`.

**Comment by DailyDreaming** [comment]
Failures:
http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/2742/
http://jenkins.cgcloud.info/job/toil-pull-requests/4449/

The new mesos version seems to take much much longer to run (in addition to some failures and some successes; this seems to be true for the non-functional PR I wrote just changing some copyright info as well), with the usual jenkins tests now timing out at 3 hours 20 minutes in the middle of the mesos promise tests.

I'm reverting the AMI to the original specific to the `jenkins-slave` for now, as I wrote another PR that updates the `coreOS` stock AMI that amazon autoscales with, and that appeared to fix some recent unexplained failures for jenkin's AWS integration tests.

**Comment by adamnovak** [comment]
@DailyDreaming How did the other PR updating CoreOS go? Did it (or is it expected to) solve the issues with the upgraded Mesos on the master branch of Toil?

**Comment by DailyDreaming** [comment]
@adamnovak I know we spoke in person, but just to be circumspect, the CoreOS PR upgraded the version of CoreOS that we use and applied a filter to fetching the AMI (which was what actually fixed the bug breaking the AWS tests, since it greatly reduced the time it took to fetch the AMI and prevented a timeout).  

It hasn't addressed upgrading `mesos`, but now that those tests are passing and the problem solved, I am going to try to merge #2372, #2382, and a PR to update the AWS instances and then do a release.  Once that's done, I'll update jenkins to use the new `mesos` and you should be able to test.

**Comment by DailyDreaming** [comment]
@adamnovak I've done a new release and set the jenkins slave to use the AMI with mesos 1.0.1.  I'd recommend a git pull from master and then rerunning the tests.

**Comment by adamnovak** [comment]
OK, there's really only one failing test left, and it is the Google Mesos sort test. It is failing because the tasks the executor starts fail, and they fail because they can't get ahold of the Google credentials which they have decided they need to talk to the job store:

```
WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Running task 0
WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Invoking command: '/mnt/ephemeral/workspace/toil-pull-requests/venv/bin/_toil_worker setup google:toil-dev:sort-test-ea66a02d-b323-438c-aa9a-bae9c8332316 job6f3069d6-aa2d-4cea-8fb4-6591c5b43084'
WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Event: {u'type': u'ACKNOWLEDGED', u'acknowledged': {u'uuid': u'u65bJuvuStqeDM6ixCAs1Q==', u'task_id': {u'value': u'0'}}}
WARNING:toil.batchSystems.mesos.batchSystem:Executor: Traceback (most recent call last):
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/bin/_toil_worker", line 9, in <module>
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     load_entry_point('toil', 'console_scripts', '_toil_worker')()
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/worker.py", line 516, in main
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     jobStore = Toil.resumeJobStore(jobStoreLocator)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 878, in resumeJobStore
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     jobStore = cls.getJobStore(locator)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/common.py", line 855, in getJobStore
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     return GoogleJobStore(rest)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/jobStores/googleJobStore.py", line 121, in __init__
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     self.storageClient = storage.Client()
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/google/cloud/storage/client.py", line 59, in __init__
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     _http=_http)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/google/cloud/client.py", line 215, in __init__
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     _ClientProjectMixin.__init__(self, project=project)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/google/cloud/client.py", line 169, in __init__
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     project = self._determine_default(project)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/google/cloud/client.py", line 182, in _determine_default
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     return _determine_default_project(project)
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/google/cloud/_helpers.py", line 179, in _determine_default_project
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     _, project = google.auth.default()
WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/mnt/ephemeral/workspace/toil-pull-requests/venv/lib/python2.7/site-packages/google/auth/_default.py", line 306, in default
WARNING:toil.batchSystems.mesos.batchSystem:Executor:     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
WARNING:toil.batchSystems.mesos.batchSystem:Executor: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.
WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Event: {u'type': u'ACKNOWLEDGED', u'acknowledged': {u'uuid': u'J2sc11XKQQaxoagGzvl7ng==', u'task_id': {u'value': u'0'}}}
WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Event: {u'type': u'ACKNOWLEDGED', u'acknowledged': {u'uuid': u'HI09buJPRl+DY1BuZiMK4g==', u'task_id': {u'value': u'0'}}}
```

I've never used Google cloud anything, so it might take some digging around to work out exactly how these credentials are supposed to be being passed.

**Comment by DailyDreaming** [comment]
@adamnovak Toil's Google auth is the simplest of the 3 clouds.  It looks for the creds in the same way that Google's `gcloud` recommends:

`export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"`
https://cloud.google.com/docs/authentication/getting-started

As long as those credentials are there for the correct account, I believe it should work.

**Comment by adamnovak** [comment]
Hm. Maybe that environment variable isn't coming through somehow? I will investigate.

**Comment by adamnovak** [comment]
OK @DailyDreaming I think that this is done. I think the one failing integration test just failed to get an AWS node in time, but I'm not sure how to rerun just the integration tests.

Can I go ahead and merge this into the "mesosUpdate" Toil branch? Then we can go to the other PR you made, and merge that into master, potentially waiting to see if another round of tests don't spontaneously fail.

**Comment by DailyDreaming** [comment]
@adamnovak Sure, go ahead and merge into the "mesosUpdate" Toil branch.  Awesome work.

**Pull request merged**
