### PR TITLE
Allow fetching job inputs for debugging

### PR DESCRIPTION
**Pull request by adamnovak**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * `toil debug-job` now has `--retrieveTaskDirectory <dir>` which will set up a job's downloaded files under `<dir>` and try to stop the job after doing the downloads. Jobs can call `self.files_downloaded_hook()` to provide a stopping point for this mode.
 * `toil debug-job` can now reconstruct the inside-the-container environment for CWL and WDL tasks.

~It still doesn't set up the paths as visible *inside* the CWL/WDL container, though, or even dump the path mappings at a high log level. And I haven't yet tested the job early-stopping hooks on the CWL side.~
 
## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
This sort of half-fixes #4815. It shows you the environment outside the container, but not what it would be like inside the container.

**Comment by adamnovak** [comment]
OK, I think I have this working.

## CWL

For CWL, if I run:
```
cat >test.cwl <<'EOF'
cwlVersion: v1.2
class: CommandLineTool
hints:
  DockerRequirement:
    dockerPull: ubuntu:20.04
baseCommand: echoo
inputs:
  message:
    type: File
    inputBinding:
      position: 1
  message2:
    type: File
    inputBinding:
      position: 2
outputs: []
EOF

touch ~/Desktop/image.png

rm -Rf tree && toil-cwl-runner --jobStore ./tree test.cwl --retryCount 0 --message test.cwl --message2 ~/Desktop/image.png

rm -Rf dumpdir
toil debug-job ./tree CWLJob --retrieveTaskDirectory dumpdir --logInfo
```
Then I get a log that ends like:
```
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.job] Job has downloaded its files. Stopping.
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Debugged job accessed files:
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Symlinked file 'files/no-job/file-730c3445d09347aa81cef16aefda1b4f/test.cwl' to path '/Users/anovak/workspace/toil/dumpdir/worker/job/tmppllnhebc.tmp'
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Symlinked file 'files/no-job/file-f380e0bcc86d44e694a50488b2c9a12a/image.png' to path '/Users/anovak/workspace/toil/dumpdir/worker/job/tmp2dpf73ma.tmp'
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.utils.toilDebugJob] Job mounted /Users/anovak/Desktop/image.png as /var/lib/cwl/stgf1016705-4b60-47c1-b62b-fc5b6a9c3bfe/image.png
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.utils.toilDebugJob] Job mounted /Users/anovak/workspace/toil/test.cwl as /var/lib/cwl/stg82b93445-2335-408f-aec4-64302e3957fc/test.cwl
[2024-04-11T18:07:22-0400] [MainThread] [I] [toil.utils.toilDebugJob] Reconstructed job container filesystem at dumpdir/inside
```
And I get a tree:
```
dumpdir
├── inside
│   └── var
│       └── lib
│           └── cwl
│               ├── stg82b93445-2335-408f-aec4-64302e3957fc
│               │   └── test.cwl -> /Users/anovak/workspace/toil/test.cwl
│               └── stgf1016705-4b60-47c1-b62b-fc5b6a9c3bfe
│                   └── image.png -> /Users/anovak/Desktop/image.png
└── worker
    └── job
        ├── tmp08n8j0nv
        │   └── tmp-outrlwmezg6
        ├── tmp2dpf73ma.tmp -> /Users/anovak/workspace/toil/tree/files/no-job/file-f380e0bcc86d44e694a50488b2c9a12a/image.png
        ├── tmp8_xb8bqc
        ├── tmpfsu4hnan
        ├── tmpg3p1gee8
        │   └── out
        └── tmppllnhebc.tmp -> /Users/anovak/workspace/toil/tree/files/no-job/file-730c3445d09347aa81cef16aefda1b4f/test.cwl

15 directories, 4 files
```

## WDL

For WDL, if I run:
```
cat >test.wdl <<'EOF'
version 1.0
workflow test {
    call make_file as f1
    call make_file as f2
    call hello {
        input:
            name_file=f1.out,
            unused_file=f2.out
    }
}
task make_file {
    input {
    }
    command <<<
        echo "These are the contents" >test.txt
    >>>
    output {
        File out = "test.txt"
    }
}
task hello {
    input {
        File name_file
        File? unused_file
    }
    command <<<
        set -e
        echoo "Hello" "$(cat ~{name_file})"
    >>>
    output {
        File out = stdout()
    }
}
EOF

rm -Rf tree && toil-wdl-runner --jobStore ./tree test.wdl --retryCount 0

rm -Rf dumpdir
toil debug-job ./tree WDLTaskJob --retrieveTaskDirectory dumpdir --logInfo
```

Then I get a log that ends like:
```
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.job] Job has downloaded its files. Stopping.
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Debugged job accessed files:
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-WDLTaskJob/instance-1qnv7m6y/file-b4b93af9b8254c65b10188d7ddbb3305/test.txt' to path '/Users/anovak/workspace/toil/dumpdir/worker/job/2c6b3dc4-1d21-4abf-9937-db475e6a6bc2/test.txt'
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-WDLTaskJob/instance-aagtgg45/file-740334367219450c8e50d7ed12522954/test.txt' to path '/Users/anovak/workspace/toil/dumpdir/worker/job/e3d724e1-e6cc-4165-97f1-6f62ab0fb1ef/test.txt'
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.utils.toilDebugJob] Job mounted /Users/anovak/workspace/toil/dumpdir/worker/job/e3d724e1-e6cc-4165-97f1-6f62ab0fb1ef/test.txt as /mnt/miniwdl_task_container/work/_miniwdl_inputs/1/test.txt
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.utils.toilDebugJob] Job mounted /Users/anovak/workspace/toil/dumpdir/worker/job/2c6b3dc4-1d21-4abf-9937-db475e6a6bc2/test.txt as /mnt/miniwdl_task_container/work/_miniwdl_inputs/0/test.txt
[2024-04-11T18:13:18-0400] [MainThread] [I] [toil.utils.toilDebugJob] Reconstructed job container filesystem at dumpdir/inside
```

And a tree that looks like:
```
dumpdir
├── inside
│   └── mnt
│       └── miniwdl_task_container
│           └── work
│               └── _miniwdl_inputs
│                   ├── 0
│                   │   └── test.txt -> ../../../../../../worker/job/2c6b3dc4-1d21-4abf-9937-db475e6a6bc2/test.txt
│                   └── 1
│                       └── test.txt -> ../../../../../../worker/job/e3d724e1-e6cc-4165-97f1-6f62ab0fb1ef/test.txt
└── worker
    └── job
        ├── 2c6b3dc4-1d21-4abf-9937-db475e6a6bc2
        │   └── test.txt
        ├── e3d724e1-e6cc-4165-97f1-6f62ab0fb1ef
        │   └── test.txt
        ├── tmpr2j5yaic
        ├── tmpxqr9__y4
        └── work

15 directories, 4 files
```

There are some extra levels of directory since I'm building a fake version of the whole container filesystem, but I think that that kind of makes the most sense to do.
```

**Comment by adamnovak** [comment]
@DailyDreaming This now has some docs and tests so I think it is really properly ready.

**Review by DailyDreaming — APPROVED** [review]
LGTM.

**Pull request merged**
