### PR TITLE
Pass cmd args to toil-wdl-runner, resolves #2721

### LINKED ISSUE #2721: toil-wdl-runner generates scripts that ignore extra arguments like --batchSystem Slurm
Hi,

So, toil has some support for wdl code via the `toil-wdl-runner`. Can this be used to submit jobs to slurm scheduler?

From the documentation, I'm doing the following:
```
$ export TOIL_SLURM_ARGS="-p noraml"
$ toil-wdl-runner --batchSystem=SLURM sleep_process.wdl sleep_process_workflow.json
Traceback (most recent call last):
  File "/igbgroup/a-m/azzaea/scalability-tst/wdl/toilwdl_compiled.py", line 1, in <module>
    from toil.job import Job
  File "/igbgroup/a-m/azzaea/scalability-tst/wdl/toil.py", line 1, in <module>
    from toil.job import Job
ImportError: No module named job
Traceback (most recent call last):
  File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/bin/toil-wdl-runner", line 11, in <module>
    sys.exit(main())
  File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/site-packages/toil/wdl/toilwdl.py", line 141, in main
    subprocess.check_call(cmd)
  File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/site-packages/subprocess32.py", line 307, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess32.CalledProcessError: Command '['python', '/igbgroup/a-m/azzaea/scalability-tst/wdl/toilwdl_compiled.py', '--batchSystem=SLURM']' returned non-zero exit status 1.
```
Where am I going wrong?

Thank you,
Azza

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-386)
┆Issue Number: TOIL-386

### PR DESCRIPTION
**Pull request by azzaea**

### CODE REVIEW

**Comment by azzaea** [comment]
Oh! I see- I guess I was working with an overly simple example, so these did not show up. Thank you for your patience and clarification. 

Will give it another shot this weekend

**Comment by azzaea** [comment]
I think the last commit may do the trick, but not sure (I couldn't run the tests on my cluster, but tried with a more complicated wdl script and toil is now able to run it successfully. Also, tried to explicitly pass the `out_dir` argument to the `toil-wdl-runner` command, and as expected, the output file is created in that directory along with the compiled python script.

Is there an alternative way to run tests on my environment? (In the cluster, I can only pip install in login nodes, but I get an error about network connection, so I can't install toil this way, and I resort to do a classical `python setup.py build & python setup.py install`)

**Comment by adamnovak** [comment]
In order to run the tests the way I described, I think you need an Internet connection to set up the virtual environment.

If there's a way to set up a virtual environment without an Internet connection, I guess you could use that. Or you could try running your tests on a different machine that has Internet access; they don't need a particularly powerful system.

The Toil makefile insists that you do everything in a virtual environment. You can also bypass it by doing:

```
TRAVIS=true python -m pytest -vv --timeout=530 src/toil/test/wdl/toilwdlTest.py::ToilWdlIntegrationTest::testPipe
```

Our Travis tests are weirdly failing to run here. I will see if I can fix them.

**Comment by DailyDreaming** [comment]
@adamnovak That's accurate.  I can take a look tomorrow and see what else would need to be reworked.

**Comment by melainalegaspi** [comment]
@adamnovak : "This will be superseded by a WDL refactor. Will close this then."

**Comment by adamnovak** [comment]
The new WDL interpreter no longer has the problems that this fixes, so I am going to close out the PR.

**Pull request closed without merging**
