### PR TITLE
Move coordination directory to places we can use

### LINKED ISSUE #4170: Toil uses `/var/run/user/$UID` if it sees it, whether or not it is actually available to Toil's current session
Hi, 

I noticed that u are using `/var/run/user/$UID` to put locally locks on files.

It creates problems on our cluster because the way our session are managed by PAM does initialize pam_systemd. I thinks it's a normal behaviour for non interactive session.

Indeed pam_systemd is the pam module responsible for creating the `/run/user/$UID` as you can read here: https://manpages.debian.org/unstable/libpam-systemd/pam_systemd.8.en.htmt

`/var/run` appears to be a symlink to `/run` however I think it's something that can vary across linux distributions.

There is an interesting discussion about using or not `/var/run/user/$UID` here: https://superuser.com/questions/1056926/is-var-run-user-uid-the-new-var-run-for-pid-files

As far as I understand this is not created by default on debian buster for non-interactive session.

Below are the file contents that I think I got from : https://packages.debian.org/fr/buster/libpam-runtime

```
$ grep 'systemd' /etc/pam.d/common-session
session optional        pam_systemd.so
$ grep 'systemd' /etc/pam.d/common-session-noninteractive
$
```

As far as I understand, beyond pam service, `/var/run/user/<uid>` can be created by any demon managed by systemd with root privileges, which is not the case of toil workers. 

Given those elements, I would not recommand using `/var/run/user/$UID` by default. I would not even recommand using it after checking that the folder exists because it might be a collision with an interactive session that is running but may stop at any time.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1199)
┆friendlyId: TOIL-1199

### PR DESCRIPTION
**Pull request by adamnovak**
Fixes #4170 by only using /var/run/user if XDG tells us we have it in our
session. Otherwise we will try other places, including /run/lock/toil. We now
make sure to mount /run/lock across form the host on Mesos and Kubernetes,
instead of /var/run/user, so we should end up using that there.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * PR submitter writes their recommendation for a changelog entry here

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Comment by adamnovak** [comment]
The integration tests failed because the test Kubernetes cluster somehow didn't set itself up, and we could never get `/etc/kubernetes/worker.ini` from it.

We should think about making `toil launch-cluster` log information from `systemd` and `journalctl` so we have at least some idea of what goes wrong when this happens in the tests.

For now I am going to rerun the test. If it fails again, I ought to be able to reproduce it manually. Maybe Kubernetes pulled some download we need to launch clusters, or something.

**Comment by adamnovak** [comment]
I had `src/toil/test/cwl/cwlTest.py::CWLWorkflowTest::test_biocontainers` fail because it decided it needed to go find the container `None`.

<details>
```
=================================== FAILURES ===================================
______________________ CWLWorkflowTest.test_biocontainers ______________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 410, in test_biocontainers
    self._tester(
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 228, in _tester
    cwltoil.main(main_args, stdout=st)
  File "/builds/databiosphere/toil/src/toil/cwl/cwltoil.py", line 3694, in main
    outobj = toil.start(wf1)
  File "/builds/databiosphere/toil/src/toil/common.py", line 999, in start
    return self._runMainLoop(rootJobDescription)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1468, in _runMainLoop
    return Leader(config=self.config,
  File "/builds/databiosphere/toil/src/toil/leader.py", line 330, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/tmp/tmpqgfaqibl' contains 1 failed jobs: 'CWLJob' seqtk_seq kind-CWLJob/instance-_5x5jc28 v6
Log from job "'CWLJob' seqtk_seq kind-CWLJob/instance-_5x5jc28 v6" follows:
=========>
	[2022-08-25T21:02:00+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2022-08-25T21:02:00+0000] [MainThread] [I] [toil] Running Toil version 5.8.0a1-5ca7b2489c75a034e8c9d520a39604336c937e46 on host runner-l96kpzps-project-3-concurrent-102zf8m.
	[2022-08-25T21:02:00+0000] [MainThread] [I] [toil.worker] Working on job 'CWLJob' seqtk_seq kind-CWLJob/instance-_5x5jc28 v4
	[2022-08-25T21:02:00+0000] [MainThread] [I] [toil.worker] Loaded body Job('CWLJob' seqtk_seq kind-CWLJob/instance-_5x5jc28 v4) from description 'CWLJob' seqtk_seq kind-CWLJob/instance-_5x5jc28 v4
	[2022-08-25T21:02:00+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [ExplicitContainerResolver[]] found description [None]
	[2022-08-25T21:02:00+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [CachedMulledDockerContainerResolver[namespace=biocontainers]] found description [None]
	[2022-08-25T21:02:00+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [CachedMulledDockerContainerResolver[namespace=local]] found description [None]
	[2022-08-25T21:02:00+0000] [MainThread] [E] [galaxy.tool_util.deps.containers] Could not get container description for tool 'None'
	Traceback (most recent call last):
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/containers.py", line 281, in find_best_container_description
	    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/containers.py", line 303, in resolve
	    container_description = container_resolver.resolve(enabled_container_types, tool_info, install=install, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/container_resolvers/mulled.py", line 534, in resolve
	    name = targets_to_mulled_name(targets=targets, hash_func=self.hash_func, namespace=self.namespace, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/container_resolvers/mulled.py", line 353, in targets_to_mulled_name
	    tags = mulled_tags_for(namespace, target.package_name, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/mulled/util.py", line 103, in mulled_tags_for
	    if not _namespace_has_repo_name(namespace, image, resolution_cache):
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/mulled/util.py", line 71, in _namespace_has_repo_name
	    return repo_name in resolution_cache.get(cache_key)
	TypeError: argument of type 'NoneType' is not iterable
	[2022-08-25T21:02:00+0000] [MainThread] [I] [cwltool] [job seqtk_seq] /tmp/55d3025d0b1c57ceb3cede5401306a7f/e487/82eb/tmpl3kuw3la/tmp-out4_kejadu$ seqtk \
	    seq \
	    -a \
	    /tmp/55d3025d0b1c57ceb3cede5401306a7f/e487/82eb/tmpupxzl5x02879ja_j/stg786b591b-234e-4f6a-a510-12c5dc2ed53b/2.fastq > /tmp/55d3025d0b1c57ceb3cede5401306a7f/e487/82eb/tmpl3kuw3la/tmp-out4_kejadu/out
	[2022-08-25T21:02:00+0000] [MainThread] [E] [cwltool] 'seqtk' not found: [Errno 2] No such file or directory: 'seqtk'
	[2022-08-25T21:02:00+0000] [MainThread] [W] [cwltool] [job seqtk_seq] completed permanentFail
	[2022-08-25T21:02:00+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2022-08-25T21:02:00+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-ef366088a6984bf0945e934ea3778b5e/2.fastq' to path '/tmp/55d3025d0b1c57ceb3cede5401306a7f/e487/82eb/tmpud3vebgk.tmp'
	Traceback (most recent call last):
	  File "/builds/databiosphere/toil/src/toil/worker.py", line 407, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/builds/databiosphere/toil/src/toil/job.py", line 2406, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/builds/databiosphere/toil/src/toil/job.py", line 2324, in _run
	    return self.run(fileStore)
	  File "/builds/databiosphere/toil/src/toil/cwl/cwltoil.py", line 2256, in run
	    raise cwltool.errors.WorkflowException(status)
	cwltool.errors.WorkflowException: permanentFail
	[2022-08-25T21:02:00+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host runner-l96kpzps-project-3-concurrent-102zf8m
<========= 
```
</details>

I ran the test myself on Courtyard (on a marginally different commit) and it passed. I don't think there's a real Toil bug here.

@mr-c Do you think the external services used in that test are reliable enough that it's more likely to fail due to a Toil bug than due to an external problem?

**Review by DailyDreaming — APPROVED** [review]
I've rerun the failing tests.  Otherwise, this LGTM.

**Comment by adamnovak** [comment]
I glommed this into #4191 so I think we should merge that one instead.

**Comment by DailyDreaming** [comment]
Closing in favor of #4191.

**Pull request closed without merging**
