### PR TITLE
Fixes jobCommand unpack

### PR DESCRIPTION
**Pull request by nikhil**
(resolves: #3603)

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Whatsits now frobnicated

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

### CODE REVIEW

**Review by DailyDreaming — APPROVED** [review]
LGTM. Thank you @nikhil .

**Comment by mr-c** [comment]
Where did the extra commands come from? Why is there no unit test for this change?

**Comment by nikhil** [comment]
Hi @mr-c, the error is caused by an extra --context value in the jobCommand:
```
_toil_worker CWLJob file:/juno/work/ci/nikhil/toil_test/tmp/jobstore kind-CWLJob/instance-9u4qkrjy --context gANjdG9pbC5iYXRjaFN5c3RlbXMuYWJzdHJhY3RCYXRjaFN5c3RlbQpXb3JrZXJDbGVhbnVwQ29udGV4dApxACmBcQF9cQIoWBEAAAB3b3JrZXJDbGVhbnVwSW5mb3EDY3RvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF0Y2hTeXN0ZW0KV29ya2VyQ2xlYW51cEluZm8KcQRYJwAAAC9qdW5vL3dvcmsvY2kvbmlraGlsL3RvaWxfdGVzdC90bXAvd29ya3EFWCQAAAA0YTM1MTMyZS1lNDg1LTQ4ZmItYThjOS00ZmEwNGI2NmRhMGNxBlgGAAAAYWx3YXlzcQeHcQiBcQlYBQAAAGFyZW5hcQpOdWIu
```
If this is not expected behavior, we should make a ticket and revert my PR. For now I add a regression test of what I did to reproduce this behavior, which was run the workflow in debug mode.

**Comment by nikhil** [comment]
Hey @mr-c and @DailyDreaming, it seems the original issue is specific to LSF systems running in debug mode. 
This is why the --debugWorker single_machine test passed, but for lsf the command was different and it fails
What are your recommendations for writing a regression test for this?
I can't seem to find the LSF test section, and this seems empty: https://github.com/DataBiosphere/toil/blob/master/src/toil/test/batchSystems/batchSystemTest.py#L844.

**Pull request merged**
