### PR TITLE
Update pickValue name

### PR DESCRIPTION
**Pull request by kaushik-work**
Follows common-workflow-language/cwl-v1.2#15

### CODE REVIEW

**Comment by mr-c** [comment]
This might need to wait for cwl version v1.2-dev3 and the corresponding `cwltool` release first

**Comment by mr-c** [comment]
No, it needs a new CWL and cwltool

**Comment by DailyDreaming** [comment]
@mr-c Roger, will wait on this then.

**Comment by mr-c** [comment]
Superseded by https://github.com/DataBiosphere/toil/pull/3092/files ; thanks @kaushik-work !

**Pull request closed without merging**
