### PR TITLE
Add support for assuming roles

### PR DESCRIPTION
**Pull request by adamnovak**
To get Toil to work with our new gi-gateway AWS account setup, we need it to be able to assume roles based on `~/.aws/config`, at least when interacting with a cluster.

This PR tracks my progress towards that goal.

### CODE REVIEW

**Comment by adamnovak** [comment]
OK, I'm now monkey patching Boto as soon as anything in the Toil module is loaded, if boto and boto3 are around. And instead of just cacheing credentials like we used to, I'm also querying boto3 to actually get the credentials. This seems to be working fine for me.

I had to patch some parts of the create-cluster/destroy-cluster flow to work under Python 3; they didn't seem to when I started. I guess we haven't tested them until now.

**Comment by adamnovak** [comment]
@DailyDreaming Since this passes tests now, can you please go ahead and review it? Especially with regard to the wisdom of my decision to replace classes inside of Boto when Toil is imported.

**Comment by benedictpaten** [comment]
@DailyDreaming Are you reviewing this, is important for CGL usage of Toil.

**Comment by adamnovak** [comment]
@DailyDreaming @joelarmstrong Could one of you please review this PR?

**Pull request merged**
