### PR TITLE
Move checkForDeadlocks() in the leader

### PR DESCRIPTION
**Pull request by jonathanxu18**

### CODE REVIEW

**Comment by jonathanxu18** [comment]
This will fix #3104.

**Review by DailyDreaming — APPROVED** [review]
@adamnovak Is there a good unit test for this, or should it be run manually and called good?

**Review by adamnovak — APPROVED** [review]
Looks like it should work to me.

**Comment by adamnovak** [comment]
I'm happy to believe @jonathanxu18's testing results, and the unit tests saying we can still detect deadlocks. Testing to see if Kubernetes job collection is "fast enough" would be nice to automate, but also is probably a lot of work, and I don't think we need it to block merging this.

**Pull request merged**
