### PR TITLE
Drop the long-deprecated cwltoil

### PR DESCRIPTION
**Pull request by mr-c**
Same entry point is provided by `toil-cwl-runner`

### CODE REVIEW

**Comment by DailyDreaming** [comment]
@mr-c We'll bump `toil` to 4.0 once we move to only python3.6+ around New Year's.  I'd like to defer breaking changes until then.  Otherwise I agree it's better to just have `toil-cwl-runner`!

**Comment by mr-c** [comment]
@DailyDreaming Sure, that is fine by me

**Comment by mr-c** [comment]
@DailyDreaming can I merge now?

**Comment by DailyDreaming** [comment]
@mr-c There's been a slight hold-up as we transition cactus, which relies on toil on our end, to python3 as well.  I'm told 2-3 weeks?  Will post here when we're ready to release 4.0.0 and include this, I'm eager to remove it too!

**Pull request merged**
